package model.paser.equipaggiamenti.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.anagrafiche.custom.AnagraficaMarche;
import model.paser.anagrafiche.custom.CodiciCasaAnagrafica;
import model.paser.equipaggiamenti.custom.AnagraficaNormalizzati;

/**
 * Class _AnagraficaUfficiali was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AnagraficaUfficiali extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODMAR_PK_COLUMN = "CODMAR";
    public static final String CODQRT_PK_COLUMN = "CODQRT";

    public static final Property<Integer> CODRAG = Property.create("codrag", Integer.class);
    public static final Property<String> DESACC = Property.create("desacc", String.class);
    public static final Property<Boolean> FLAGPA = Property.create("flagpa", Boolean.class);
    public static final Property<Integer> OPTRAG = Property.create("optrag", Integer.class);
    public static final Property<AnagraficaMarche> ANAGRAFICA_MARCHE = Property.create("anagraficaMarche", AnagraficaMarche.class);
    public static final Property<AnagraficaNormalizzati> ANAGRAFICA_NORMALIZZATI = Property.create("anagraficaNormalizzati", AnagraficaNormalizzati.class);
    public static final Property<CodiciCasaAnagrafica> CODICI_CASA_ANAGRAFICA = Property.create("codiciCasaAnagrafica", CodiciCasaAnagrafica.class);

    public void setCodrag(int codrag) {
        writeProperty("codrag", codrag);
    }
    public int getCodrag() {
        Object value = readProperty("codrag");
        return (value != null) ? (Integer) value : 0;
    }

    public void setDesacc(String desacc) {
        writeProperty("desacc", desacc);
    }
    public String getDesacc() {
        return (String)readProperty("desacc");
    }

    public void setFlagpa(boolean flagpa) {
        writeProperty("flagpa", flagpa);
    }
	public boolean isFlagpa() {
        Boolean value = (Boolean)readProperty("flagpa");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setOptrag(int optrag) {
        writeProperty("optrag", optrag);
    }
    public int getOptrag() {
        Object value = readProperty("optrag");
        return (value != null) ? (Integer) value : 0;
    }

    public void setAnagraficaMarche(AnagraficaMarche anagraficaMarche) {
        setToOneTarget("anagraficaMarche", anagraficaMarche, true);
    }

    public AnagraficaMarche getAnagraficaMarche() {
        return (AnagraficaMarche)readProperty("anagraficaMarche");
    }


    public void setAnagraficaNormalizzati(AnagraficaNormalizzati anagraficaNormalizzati) {
        setToOneTarget("anagraficaNormalizzati", anagraficaNormalizzati, true);
    }

    public AnagraficaNormalizzati getAnagraficaNormalizzati() {
        return (AnagraficaNormalizzati)readProperty("anagraficaNormalizzati");
    }


    public void setCodiciCasaAnagrafica(CodiciCasaAnagrafica codiciCasaAnagrafica) {
        setToOneTarget("codiciCasaAnagrafica", codiciCasaAnagrafica, true);
    }

    public CodiciCasaAnagrafica getCodiciCasaAnagrafica() {
        return (CodiciCasaAnagrafica)readProperty("codiciCasaAnagrafica");
    }


}
