package model.paser.equipaggiamenti.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.equipaggiamenti.custom.Esclusioni;
import model.paser.equipaggiamenti.custom.Inclusioni;
import model.paser.equipaggiamenti.custom.Vincoli;

/**
 * Class _ComposizionePacchetti was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ComposizionePacchetti extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODQRE_PK_COLUMN = "CODQRE";
    public static final String CODQRP_PK_COLUMN = "CODQRP";

    public static final Property<List<Esclusioni>> ESCLUSIONIS = Property.create("esclusionis", List.class);
    public static final Property<List<Esclusioni>> ESCLUSIONIS1 = Property.create("esclusionis1", List.class);
    public static final Property<List<Inclusioni>> INCLUSIONIS = Property.create("inclusionis", List.class);
    public static final Property<List<Inclusioni>> INCLUSIONIS1 = Property.create("inclusionis1", List.class);
    public static final Property<List<Vincoli>> VINCOLIS = Property.create("vincolis", List.class);
    public static final Property<List<Vincoli>> VINCOLIS1 = Property.create("vincolis1", List.class);

    public void addToEsclusionis(Esclusioni obj) {
        addToManyTarget("esclusionis", obj, true);
    }
    public void removeFromEsclusionis(Esclusioni obj) {
        removeToManyTarget("esclusionis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Esclusioni> getEsclusionis() {
        return (List<Esclusioni>)readProperty("esclusionis");
    }


    public void addToEsclusionis1(Esclusioni obj) {
        addToManyTarget("esclusionis1", obj, true);
    }
    public void removeFromEsclusionis1(Esclusioni obj) {
        removeToManyTarget("esclusionis1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Esclusioni> getEsclusionis1() {
        return (List<Esclusioni>)readProperty("esclusionis1");
    }


    public void addToInclusionis(Inclusioni obj) {
        addToManyTarget("inclusionis", obj, true);
    }
    public void removeFromInclusionis(Inclusioni obj) {
        removeToManyTarget("inclusionis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Inclusioni> getInclusionis() {
        return (List<Inclusioni>)readProperty("inclusionis");
    }


    public void addToInclusionis1(Inclusioni obj) {
        addToManyTarget("inclusionis1", obj, true);
    }
    public void removeFromInclusionis1(Inclusioni obj) {
        removeToManyTarget("inclusionis1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Inclusioni> getInclusionis1() {
        return (List<Inclusioni>)readProperty("inclusionis1");
    }


    public void addToVincolis(Vincoli obj) {
        addToManyTarget("vincolis", obj, true);
    }
    public void removeFromVincolis(Vincoli obj) {
        removeToManyTarget("vincolis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Vincoli> getVincolis() {
        return (List<Vincoli>)readProperty("vincolis");
    }


    public void addToVincolis1(Vincoli obj) {
        addToManyTarget("vincolis1", obj, true);
    }
    public void removeFromVincolis1(Vincoli obj) {
        removeToManyTarget("vincolis1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Vincoli> getVincolis1() {
        return (List<Vincoli>)readProperty("vincolis1");
    }


}
