package model.paser.equipaggiamenti.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.equipaggiamenti.custom.AnagraficaStatus;
import model.paser.identificazione.custom.Base;

/**
 * Class _ListiniUfficiali was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ListiniUfficiali extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANNOXX_PK_COLUMN = "ANNOXX";
    public static final String CODALL_PK_COLUMN = "CODALL";
    public static final String CODQRT_PK_COLUMN = "CODQRT";
    public static final String DATACO_PK_COLUMN = "DATACO";
    public static final String DATAVA_PK_COLUMN = "DATAVA";
    public static final String MESEXX_PK_COLUMN = "MESEXX";

    public static final Property<Boolean> FLAUFF = Property.create("flauff", Boolean.class);
    public static final Property<Double> PREZEU = Property.create("prezeu", Double.class);
    public static final Property<AnagraficaStatus> ANAGRAFICA_STATUS = Property.create("anagraficaStatus", AnagraficaStatus.class);
    public static final Property<Base> BASE = Property.create("base", Base.class);
    public static final Property<Base> BASE1 = Property.create("base1", Base.class);
    public static final Property<Base> BASE2 = Property.create("base2", Base.class);

    public void setFlauff(boolean flauff) {
        writeProperty("flauff", flauff);
    }
	public boolean isFlauff() {
        Boolean value = (Boolean)readProperty("flauff");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setPrezeu(double prezeu) {
        writeProperty("prezeu", prezeu);
    }
    public double getPrezeu() {
        Object value = readProperty("prezeu");
        return (value != null) ? (Double) value : 0;
    }

    public void setAnagraficaStatus(AnagraficaStatus anagraficaStatus) {
        setToOneTarget("anagraficaStatus", anagraficaStatus, true);
    }

    public AnagraficaStatus getAnagraficaStatus() {
        return (AnagraficaStatus)readProperty("anagraficaStatus");
    }


    public void setBase(Base base) {
        setToOneTarget("base", base, true);
    }

    public Base getBase() {
        return (Base)readProperty("base");
    }


    public void setBase1(Base base1) {
        setToOneTarget("base1", base1, true);
    }

    public Base getBase1() {
        return (Base)readProperty("base1");
    }


    public void setBase2(Base base2) {
        setToOneTarget("base2", base2, true);
    }

    public Base getBase2() {
        return (Base)readProperty("base2");
    }


}
