package model.paser.usato.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.usato.custom.Quotazioni;

/**
 * Class _ChilometraggioStandardComplessivo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ChilometraggioStandardComplessivo extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String INDKM_PK_COLUMN = "INDKM";

    public static final Property<Integer> KMTOT01 = Property.create("kmtot01", Integer.class);
    public static final Property<Integer> KMTOT02 = Property.create("kmtot02", Integer.class);
    public static final Property<Integer> KMTOT03 = Property.create("kmtot03", Integer.class);
    public static final Property<Integer> KMTOT04 = Property.create("kmtot04", Integer.class);
    public static final Property<Integer> KMTOT05 = Property.create("kmtot05", Integer.class);
    public static final Property<Integer> KMTOT06 = Property.create("kmtot06", Integer.class);
    public static final Property<Integer> KMTOT07 = Property.create("kmtot07", Integer.class);
    public static final Property<Integer> KMTOT08 = Property.create("kmtot08", Integer.class);
    public static final Property<Integer> KMTOT09 = Property.create("kmtot09", Integer.class);
    public static final Property<Integer> KMTOT10 = Property.create("kmtot10", Integer.class);
    public static final Property<Integer> KMTOT11 = Property.create("kmtot11", Integer.class);
    public static final Property<Integer> KMTOT12 = Property.create("kmtot12", Integer.class);
    public static final Property<Integer> KMTOT13 = Property.create("kmtot13", Integer.class);
    public static final Property<Integer> KMTOT14 = Property.create("kmtot14", Integer.class);
    public static final Property<Integer> KMTOT15 = Property.create("kmtot15", Integer.class);
    public static final Property<Integer> KMTOT16 = Property.create("kmtot16", Integer.class);
    public static final Property<List<Quotazioni>> QUOTAZIONIS = Property.create("quotazionis", List.class);

    public void setKmtot01(int kmtot01) {
        writeProperty("kmtot01", kmtot01);
    }
    public int getKmtot01() {
        Object value = readProperty("kmtot01");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot02(int kmtot02) {
        writeProperty("kmtot02", kmtot02);
    }
    public int getKmtot02() {
        Object value = readProperty("kmtot02");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot03(int kmtot03) {
        writeProperty("kmtot03", kmtot03);
    }
    public int getKmtot03() {
        Object value = readProperty("kmtot03");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot04(int kmtot04) {
        writeProperty("kmtot04", kmtot04);
    }
    public int getKmtot04() {
        Object value = readProperty("kmtot04");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot05(int kmtot05) {
        writeProperty("kmtot05", kmtot05);
    }
    public int getKmtot05() {
        Object value = readProperty("kmtot05");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot06(int kmtot06) {
        writeProperty("kmtot06", kmtot06);
    }
    public int getKmtot06() {
        Object value = readProperty("kmtot06");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot07(int kmtot07) {
        writeProperty("kmtot07", kmtot07);
    }
    public int getKmtot07() {
        Object value = readProperty("kmtot07");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot08(int kmtot08) {
        writeProperty("kmtot08", kmtot08);
    }
    public int getKmtot08() {
        Object value = readProperty("kmtot08");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot09(int kmtot09) {
        writeProperty("kmtot09", kmtot09);
    }
    public int getKmtot09() {
        Object value = readProperty("kmtot09");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot10(int kmtot10) {
        writeProperty("kmtot10", kmtot10);
    }
    public int getKmtot10() {
        Object value = readProperty("kmtot10");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot11(int kmtot11) {
        writeProperty("kmtot11", kmtot11);
    }
    public int getKmtot11() {
        Object value = readProperty("kmtot11");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot12(int kmtot12) {
        writeProperty("kmtot12", kmtot12);
    }
    public int getKmtot12() {
        Object value = readProperty("kmtot12");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot13(int kmtot13) {
        writeProperty("kmtot13", kmtot13);
    }
    public int getKmtot13() {
        Object value = readProperty("kmtot13");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot14(int kmtot14) {
        writeProperty("kmtot14", kmtot14);
    }
    public int getKmtot14() {
        Object value = readProperty("kmtot14");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot15(int kmtot15) {
        writeProperty("kmtot15", kmtot15);
    }
    public int getKmtot15() {
        Object value = readProperty("kmtot15");
        return (value != null) ? (Integer) value : 0;
    }

    public void setKmtot16(int kmtot16) {
        writeProperty("kmtot16", kmtot16);
    }
    public int getKmtot16() {
        Object value = readProperty("kmtot16");
        return (value != null) ? (Integer) value : 0;
    }

    public void addToQuotazionis(Quotazioni obj) {
        addToManyTarget("quotazionis", obj, true);
    }
    public void removeFromQuotazionis(Quotazioni obj) {
        removeToManyTarget("quotazionis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Quotazioni> getQuotazionis() {
        return (List<Quotazioni>)readProperty("quotazionis");
    }


}
