package model.paser.usato.cayenne;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _EdizioneQuotazioni was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EdizioneQuotazioni extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANNOED_PK_COLUMN = "ANNOED";
    public static final String MESEED_PK_COLUMN = "MESEED";


}
