package model.paser.usato.cayenne;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Intestazione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Intestazione extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String PERI01_PK_COLUMN = "PERI01";
    public static final String PERI02_PK_COLUMN = "PERI02";
    public static final String PERI03_PK_COLUMN = "PERI03";
    public static final String PERI04_PK_COLUMN = "PERI04";
    public static final String PERI05_PK_COLUMN = "PERI05";
    public static final String PERI06_PK_COLUMN = "PERI06";
    public static final String PERI07_PK_COLUMN = "PERI07";
    public static final String PERI08_PK_COLUMN = "PERI08";
    public static final String PERI09_PK_COLUMN = "PERI09";
    public static final String PERI10_PK_COLUMN = "PERI10";
    public static final String PERI11_PK_COLUMN = "PERI11";
    public static final String PERI12_PK_COLUMN = "PERI12";
    public static final String PERI13_PK_COLUMN = "PERI13";
    public static final String PERI14_PK_COLUMN = "PERI14";
    public static final String PERI15_PK_COLUMN = "PERI15";
    public static final String PERI16_PK_COLUMN = "PERI16";


}
