package model.paser.usato.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.identificazione.custom.Base;
import model.paser.usato.custom.ChilometraggioStandardComplessivo;

/**
 * Class _Quotazioni was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Quotazioni extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANNOXX_PK_COLUMN = "ANNOXX";
    public static final String CODALL_PK_COLUMN = "CODALL";
    public static final String MESEXX_PK_COLUMN = "MESEXX";

    public static final Property<Integer> USAE01 = Property.create("usae01", Integer.class);
    public static final Property<Integer> USAE02 = Property.create("usae02", Integer.class);
    public static final Property<Integer> USAE03 = Property.create("usae03", Integer.class);
    public static final Property<Integer> USAE04 = Property.create("usae04", Integer.class);
    public static final Property<Integer> USAE05 = Property.create("usae05", Integer.class);
    public static final Property<Integer> USAE06 = Property.create("usae06", Integer.class);
    public static final Property<Integer> USAE07 = Property.create("usae07", Integer.class);
    public static final Property<Integer> USAE08 = Property.create("usae08", Integer.class);
    public static final Property<Integer> USAE09 = Property.create("usae09", Integer.class);
    public static final Property<Integer> USAE10 = Property.create("usae10", Integer.class);
    public static final Property<Integer> USAE11 = Property.create("usae11", Integer.class);
    public static final Property<Integer> USAE12 = Property.create("usae12", Integer.class);
    public static final Property<Integer> USAE13 = Property.create("usae13", Integer.class);
    public static final Property<Integer> USAE14 = Property.create("usae14", Integer.class);
    public static final Property<Integer> USAE15 = Property.create("usae15", Integer.class);
    public static final Property<Integer> USAE16 = Property.create("usae16", Integer.class);
    public static final Property<Integer> USAR01 = Property.create("usar01", Integer.class);
    public static final Property<Integer> USAR02 = Property.create("usar02", Integer.class);
    public static final Property<Integer> USAR03 = Property.create("usar03", Integer.class);
    public static final Property<Integer> USAR04 = Property.create("usar04", Integer.class);
    public static final Property<Integer> USAR05 = Property.create("usar05", Integer.class);
    public static final Property<Integer> USAR06 = Property.create("usar06", Integer.class);
    public static final Property<Integer> USAR07 = Property.create("usar07", Integer.class);
    public static final Property<Integer> USAR08 = Property.create("usar08", Integer.class);
    public static final Property<Integer> USAR09 = Property.create("usar09", Integer.class);
    public static final Property<Integer> USAR10 = Property.create("usar10", Integer.class);
    public static final Property<Integer> USAR11 = Property.create("usar11", Integer.class);
    public static final Property<Integer> USAR12 = Property.create("usar12", Integer.class);
    public static final Property<Integer> USAR13 = Property.create("usar13", Integer.class);
    public static final Property<Integer> USAR14 = Property.create("usar14", Integer.class);
    public static final Property<Integer> USAR15 = Property.create("usar15", Integer.class);
    public static final Property<Integer> USAR16 = Property.create("usar16", Integer.class);
    public static final Property<Base> BASE = Property.create("base", Base.class);
    public static final Property<Base> BASE1 = Property.create("base1", Base.class);
    public static final Property<Base> BASE2 = Property.create("base2", Base.class);
    public static final Property<ChilometraggioStandardComplessivo> CHILOMETRAGGIO_STANDARD_COMPLESSIVO = Property.create("chilometraggioStandardComplessivo", ChilometraggioStandardComplessivo.class);

    public void setUsae01(int usae01) {
        writeProperty("usae01", usae01);
    }
    public int getUsae01() {
        Object value = readProperty("usae01");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae02(int usae02) {
        writeProperty("usae02", usae02);
    }
    public int getUsae02() {
        Object value = readProperty("usae02");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae03(int usae03) {
        writeProperty("usae03", usae03);
    }
    public int getUsae03() {
        Object value = readProperty("usae03");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae04(int usae04) {
        writeProperty("usae04", usae04);
    }
    public int getUsae04() {
        Object value = readProperty("usae04");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae05(int usae05) {
        writeProperty("usae05", usae05);
    }
    public int getUsae05() {
        Object value = readProperty("usae05");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae06(int usae06) {
        writeProperty("usae06", usae06);
    }
    public int getUsae06() {
        Object value = readProperty("usae06");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae07(int usae07) {
        writeProperty("usae07", usae07);
    }
    public int getUsae07() {
        Object value = readProperty("usae07");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae08(int usae08) {
        writeProperty("usae08", usae08);
    }
    public int getUsae08() {
        Object value = readProperty("usae08");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae09(int usae09) {
        writeProperty("usae09", usae09);
    }
    public int getUsae09() {
        Object value = readProperty("usae09");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae10(int usae10) {
        writeProperty("usae10", usae10);
    }
    public int getUsae10() {
        Object value = readProperty("usae10");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae11(int usae11) {
        writeProperty("usae11", usae11);
    }
    public int getUsae11() {
        Object value = readProperty("usae11");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae12(int usae12) {
        writeProperty("usae12", usae12);
    }
    public int getUsae12() {
        Object value = readProperty("usae12");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae13(int usae13) {
        writeProperty("usae13", usae13);
    }
    public int getUsae13() {
        Object value = readProperty("usae13");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae14(int usae14) {
        writeProperty("usae14", usae14);
    }
    public int getUsae14() {
        Object value = readProperty("usae14");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae15(int usae15) {
        writeProperty("usae15", usae15);
    }
    public int getUsae15() {
        Object value = readProperty("usae15");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsae16(int usae16) {
        writeProperty("usae16", usae16);
    }
    public int getUsae16() {
        Object value = readProperty("usae16");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar01(int usar01) {
        writeProperty("usar01", usar01);
    }
    public int getUsar01() {
        Object value = readProperty("usar01");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar02(int usar02) {
        writeProperty("usar02", usar02);
    }
    public int getUsar02() {
        Object value = readProperty("usar02");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar03(int usar03) {
        writeProperty("usar03", usar03);
    }
    public int getUsar03() {
        Object value = readProperty("usar03");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar04(int usar04) {
        writeProperty("usar04", usar04);
    }
    public int getUsar04() {
        Object value = readProperty("usar04");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar05(int usar05) {
        writeProperty("usar05", usar05);
    }
    public int getUsar05() {
        Object value = readProperty("usar05");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar06(int usar06) {
        writeProperty("usar06", usar06);
    }
    public int getUsar06() {
        Object value = readProperty("usar06");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar07(int usar07) {
        writeProperty("usar07", usar07);
    }
    public int getUsar07() {
        Object value = readProperty("usar07");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar08(int usar08) {
        writeProperty("usar08", usar08);
    }
    public int getUsar08() {
        Object value = readProperty("usar08");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar09(int usar09) {
        writeProperty("usar09", usar09);
    }
    public int getUsar09() {
        Object value = readProperty("usar09");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar10(int usar10) {
        writeProperty("usar10", usar10);
    }
    public int getUsar10() {
        Object value = readProperty("usar10");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar11(int usar11) {
        writeProperty("usar11", usar11);
    }
    public int getUsar11() {
        Object value = readProperty("usar11");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar12(int usar12) {
        writeProperty("usar12", usar12);
    }
    public int getUsar12() {
        Object value = readProperty("usar12");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar13(int usar13) {
        writeProperty("usar13", usar13);
    }
    public int getUsar13() {
        Object value = readProperty("usar13");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar14(int usar14) {
        writeProperty("usar14", usar14);
    }
    public int getUsar14() {
        Object value = readProperty("usar14");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar15(int usar15) {
        writeProperty("usar15", usar15);
    }
    public int getUsar15() {
        Object value = readProperty("usar15");
        return (value != null) ? (Integer) value : 0;
    }

    public void setUsar16(int usar16) {
        writeProperty("usar16", usar16);
    }
    public int getUsar16() {
        Object value = readProperty("usar16");
        return (value != null) ? (Integer) value : 0;
    }

    public void setBase(Base base) {
        setToOneTarget("base", base, true);
    }

    public Base getBase() {
        return (Base)readProperty("base");
    }


    public void setBase1(Base base1) {
        setToOneTarget("base1", base1, true);
    }

    public Base getBase1() {
        return (Base)readProperty("base1");
    }


    public void setBase2(Base base2) {
        setToOneTarget("base2", base2, true);
    }

    public Base getBase2() {
        return (Base)readProperty("base2");
    }


    public void setChilometraggioStandardComplessivo(ChilometraggioStandardComplessivo chilometraggioStandardComplessivo) {
        setToOneTarget("chilometraggioStandardComplessivo", chilometraggioStandardComplessivo, true);
    }

    public ChilometraggioStandardComplessivo getChilometraggioStandardComplessivo() {
        return (ChilometraggioStandardComplessivo)readProperty("chilometraggioStandardComplessivo");
    }


}
