package model.paser.anagrafiche.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.anagrafiche.custom.AnagraficaMarche;
import model.paser.anagrafiche.custom.AnagraficaModelli;
import model.paser.identificazione.custom.Base;

/**
 * Class _AnagraficaAllestimenti was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AnagraficaAllestimenti extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODALL_PK_COLUMN = "CODALL";
    public static final String CODMAR_PK_COLUMN = "CODMAR";
    public static final String CODMOD_PK_COLUMN = "CODMOD";

    public static final Property<String> DESALL = Property.create("desall", String.class);
    public static final Property<String> DESALM = Property.create("desalm", String.class);
    public static final Property<AnagraficaMarche> ANAGRAFICA_MARCHE = Property.create("anagraficaMarche", AnagraficaMarche.class);
    public static final Property<AnagraficaModelli> ANAGRAFICA_MODELLI = Property.create("anagraficaModelli", AnagraficaModelli.class);
    public static final Property<Base> BASE = Property.create("base", Base.class);

    public void setDesall(String desall) {
        writeProperty("desall", desall);
    }
    public String getDesall() {
        return (String)readProperty("desall");
    }

    public void setDesalm(String desalm) {
        writeProperty("desalm", desalm);
    }
    public String getDesalm() {
        return (String)readProperty("desalm");
    }

    public void setAnagraficaMarche(AnagraficaMarche anagraficaMarche) {
        setToOneTarget("anagraficaMarche", anagraficaMarche, true);
    }

    public AnagraficaMarche getAnagraficaMarche() {
        return (AnagraficaMarche)readProperty("anagraficaMarche");
    }


    public void setAnagraficaModelli(AnagraficaModelli anagraficaModelli) {
        setToOneTarget("anagraficaModelli", anagraficaModelli, true);
    }

    public AnagraficaModelli getAnagraficaModelli() {
        return (AnagraficaModelli)readProperty("anagraficaModelli");
    }


    public void setBase(Base base) {
        setToOneTarget("base", base, true);
    }

    public Base getBase() {
        return (Base)readProperty("base");
    }


}
