package model.paser.anagrafiche.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.anagrafiche.custom.AnagraficaAllestimenti;
import model.paser.anagrafiche.custom.AnagraficaMarche;
import model.paser.anagrafiche.custom.CrossRaggruppamentoModelli;

/**
 * Class _AnagraficaModelli was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AnagraficaModelli extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODMAR_PK_COLUMN = "CODMAR";
    public static final String CODMOD_PK_COLUMN = "CODMOD";

    public static final Property<String> DESMOD = Property.create("desmod", String.class);
    public static final Property<String> DESMOM = Property.create("desmom", String.class);
    public static final Property<Boolean> FLAGM2 = Property.create("flagm2", Boolean.class);
    public static final Property<List<AnagraficaAllestimenti>> ANAGRAFICA_ALLESTIMENTIS = Property.create("anagraficaAllestimentis", List.class);
    public static final Property<AnagraficaMarche> ANAGRAFICA_MARCHE = Property.create("anagraficaMarche", AnagraficaMarche.class);
    public static final Property<List<CrossRaggruppamentoModelli>> CROSS_RAGGRUPPAMENTO_MODELLIS = Property.create("crossRaggruppamentoModellis", List.class);

    public void setDesmod(String desmod) {
        writeProperty("desmod", desmod);
    }
    public String getDesmod() {
        return (String)readProperty("desmod");
    }

    public void setDesmom(String desmom) {
        writeProperty("desmom", desmom);
    }
    public String getDesmom() {
        return (String)readProperty("desmom");
    }

    public void setFlagm2(boolean flagm2) {
        writeProperty("flagm2", flagm2);
    }
	public boolean isFlagm2() {
        Boolean value = (Boolean)readProperty("flagm2");
        return (value != null) ? value.booleanValue() : false;
    }

    public void addToAnagraficaAllestimentis(AnagraficaAllestimenti obj) {
        addToManyTarget("anagraficaAllestimentis", obj, true);
    }
    public void removeFromAnagraficaAllestimentis(AnagraficaAllestimenti obj) {
        removeToManyTarget("anagraficaAllestimentis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AnagraficaAllestimenti> getAnagraficaAllestimentis() {
        return (List<AnagraficaAllestimenti>)readProperty("anagraficaAllestimentis");
    }


    public void setAnagraficaMarche(AnagraficaMarche anagraficaMarche) {
        setToOneTarget("anagraficaMarche", anagraficaMarche, true);
    }

    public AnagraficaMarche getAnagraficaMarche() {
        return (AnagraficaMarche)readProperty("anagraficaMarche");
    }


    public void addToCrossRaggruppamentoModellis(CrossRaggruppamentoModelli obj) {
        addToManyTarget("crossRaggruppamentoModellis", obj, true);
    }
    public void removeFromCrossRaggruppamentoModellis(CrossRaggruppamentoModelli obj) {
        removeToManyTarget("crossRaggruppamentoModellis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CrossRaggruppamentoModelli> getCrossRaggruppamentoModellis() {
        return (List<CrossRaggruppamentoModelli>)readProperty("crossRaggruppamentoModellis");
    }


}
