package model.paser.anagrafiche.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.anagrafiche.custom.AnagraficaMarche;
import model.paser.anagrafiche.custom.CrossRaggruppamentoModelli;

/**
 * Class _AnagraficaRaggruppamentoModelli was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AnagraficaRaggruppamentoModelli extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODMOR_PK_COLUMN = "CODMOR";

    public static final Property<String> DESMOR = Property.create("desmor", String.class);
    public static final Property<AnagraficaMarche> ANAGRAFICA_MARCHE = Property.create("anagraficaMarche", AnagraficaMarche.class);
    public static final Property<List<CrossRaggruppamentoModelli>> CROSS_RAGGRUPPAMENTO_MODELLIS = Property.create("crossRaggruppamentoModellis", List.class);

    public void setDesmor(String desmor) {
        writeProperty("desmor", desmor);
    }
    public String getDesmor() {
        return (String)readProperty("desmor");
    }

    public void setAnagraficaMarche(AnagraficaMarche anagraficaMarche) {
        setToOneTarget("anagraficaMarche", anagraficaMarche, true);
    }

    public AnagraficaMarche getAnagraficaMarche() {
        return (AnagraficaMarche)readProperty("anagraficaMarche");
    }


    public void addToCrossRaggruppamentoModellis(CrossRaggruppamentoModelli obj) {
        addToManyTarget("crossRaggruppamentoModellis", obj, true);
    }
    public void removeFromCrossRaggruppamentoModellis(CrossRaggruppamentoModelli obj) {
        removeToManyTarget("crossRaggruppamentoModellis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CrossRaggruppamentoModelli> getCrossRaggruppamentoModellis() {
        return (List<CrossRaggruppamentoModelli>)readProperty("crossRaggruppamentoModellis");
    }


}
