package model.paser.anagrafiche.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.anagrafiche.custom.AnagraficaAllestimenti;
import model.paser.anagrafiche.custom.AnagraficaModelli;
import model.paser.anagrafiche.custom.AnagraficaRaggruppamentoModelli;
import model.paser.anagrafiche.custom.CrossRaggruppamentoModelli;
import model.paser.equipaggiamenti.custom.AnagraficaUfficiali;

/**
 * Class _AnagraficaMarche was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AnagraficaMarche extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODMAR_PK_COLUMN = "CODMAR";

    public static final Property<String> DESMAR = Property.create("desmar", String.class);
    public static final Property<String> INDINT = Property.create("indint", String.class);
    public static final Property<List<AnagraficaAllestimenti>> ANAGRAFICA_ALLESTIMENTIS = Property.create("anagraficaAllestimentis", List.class);
    public static final Property<List<AnagraficaModelli>> ANAGRAFICA_MODELLIS = Property.create("anagraficaModellis", List.class);
    public static final Property<List<AnagraficaRaggruppamentoModelli>> ANAGRAFICA_RAGGRUPPAMENTO_MODELLIS = Property.create("anagraficaRaggruppamentoModellis", List.class);
    public static final Property<List<AnagraficaUfficiali>> ANAGRAFICA_UFFICIALIS = Property.create("anagraficaUfficialis", List.class);
    public static final Property<List<CrossRaggruppamentoModelli>> CROSS_RAGGRUPPAMENTO_MODELLIS = Property.create("crossRaggruppamentoModellis", List.class);

    public void setDesmar(String desmar) {
        writeProperty("desmar", desmar);
    }
    public String getDesmar() {
        return (String)readProperty("desmar");
    }

    public void setIndint(String indint) {
        writeProperty("indint", indint);
    }
    public String getIndint() {
        return (String)readProperty("indint");
    }

    public void addToAnagraficaAllestimentis(AnagraficaAllestimenti obj) {
        addToManyTarget("anagraficaAllestimentis", obj, true);
    }
    public void removeFromAnagraficaAllestimentis(AnagraficaAllestimenti obj) {
        removeToManyTarget("anagraficaAllestimentis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AnagraficaAllestimenti> getAnagraficaAllestimentis() {
        return (List<AnagraficaAllestimenti>)readProperty("anagraficaAllestimentis");
    }


    public void addToAnagraficaModellis(AnagraficaModelli obj) {
        addToManyTarget("anagraficaModellis", obj, true);
    }
    public void removeFromAnagraficaModellis(AnagraficaModelli obj) {
        removeToManyTarget("anagraficaModellis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AnagraficaModelli> getAnagraficaModellis() {
        return (List<AnagraficaModelli>)readProperty("anagraficaModellis");
    }


    public void addToAnagraficaRaggruppamentoModellis(AnagraficaRaggruppamentoModelli obj) {
        addToManyTarget("anagraficaRaggruppamentoModellis", obj, true);
    }
    public void removeFromAnagraficaRaggruppamentoModellis(AnagraficaRaggruppamentoModelli obj) {
        removeToManyTarget("anagraficaRaggruppamentoModellis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AnagraficaRaggruppamentoModelli> getAnagraficaRaggruppamentoModellis() {
        return (List<AnagraficaRaggruppamentoModelli>)readProperty("anagraficaRaggruppamentoModellis");
    }


    public void addToAnagraficaUfficialis(AnagraficaUfficiali obj) {
        addToManyTarget("anagraficaUfficialis", obj, true);
    }
    public void removeFromAnagraficaUfficialis(AnagraficaUfficiali obj) {
        removeToManyTarget("anagraficaUfficialis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AnagraficaUfficiali> getAnagraficaUfficialis() {
        return (List<AnagraficaUfficiali>)readProperty("anagraficaUfficialis");
    }


    public void addToCrossRaggruppamentoModellis(CrossRaggruppamentoModelli obj) {
        addToManyTarget("crossRaggruppamentoModellis", obj, true);
    }
    public void removeFromCrossRaggruppamentoModellis(CrossRaggruppamentoModelli obj) {
        removeToManyTarget("crossRaggruppamentoModellis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CrossRaggruppamentoModelli> getCrossRaggruppamentoModellis() {
        return (List<CrossRaggruppamentoModelli>)readProperty("crossRaggruppamentoModellis");
    }


}
