package model.paser.anagrafiche.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.usato.custom.InformazioniAggiuntiveUsato;

/**
 * Class _AnagraficaMotivazioniPeriodiQuotazioniUsato was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AnagraficaMotivazioniPeriodiQuotazioniUsato extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODMOQ_PK_COLUMN = "CODMOQ";

    public static final Property<String> DESMOQ = Property.create("desmoq", String.class);
    public static final Property<List<InformazioniAggiuntiveUsato>> INFORMAZIONI_AGGIUNTIVE_USATOES = Property.create("informazioniAggiuntiveUsatoes", List.class);

    public void setDesmoq(String desmoq) {
        writeProperty("desmoq", desmoq);
    }
    public String getDesmoq() {
        return (String)readProperty("desmoq");
    }

    public void addToInformazioniAggiuntiveUsatoes(InformazioniAggiuntiveUsato obj) {
        addToManyTarget("informazioniAggiuntiveUsatoes", obj, true);
    }
    public void removeFromInformazioniAggiuntiveUsatoes(InformazioniAggiuntiveUsato obj) {
        removeToManyTarget("informazioniAggiuntiveUsatoes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InformazioniAggiuntiveUsato> getInformazioniAggiuntiveUsatoes() {
        return (List<InformazioniAggiuntiveUsato>)readProperty("informazioniAggiuntiveUsatoes");
    }


}
