package model.paser.anagrafiche.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.identificazione.custom.Base;

/**
 * Class _CategoriaVeicolo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CategoriaVeicolo extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODTVE_PK_COLUMN = "CODTVE";

    public static final Property<String> CATVCL = Property.create("catvcl", String.class);
    public static final Property<Boolean> CATVEI = Property.create("catvei", Boolean.class);
    public static final Property<String> CVEDES = Property.create("cvedes", String.class);
    public static final Property<List<Base>> BASES = Property.create("bases", List.class);

    public void setCatvcl(String catvcl) {
        writeProperty("catvcl", catvcl);
    }
    public String getCatvcl() {
        return (String)readProperty("catvcl");
    }

    public void setCatvei(boolean catvei) {
        writeProperty("catvei", catvei);
    }
	public boolean isCatvei() {
        Boolean value = (Boolean)readProperty("catvei");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setCvedes(String cvedes) {
        writeProperty("cvedes", cvedes);
    }
    public String getCvedes() {
        return (String)readProperty("cvedes");
    }

    public void addToBases(Base obj) {
        addToManyTarget("bases", obj, true);
    }
    public void removeFromBases(Base obj) {
        removeToManyTarget("bases", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Base> getBases() {
        return (List<Base>)readProperty("bases");
    }


}
