package model.paser.anagrafiche.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.equipaggiamenti.custom.AnagraficaUfficiali;
import model.paser.identificazione.custom.CodiciCasaIdentificazione;

/**
 * Class _CodiciCasaAnagrafica was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CodiciCasaAnagrafica extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODCAS_PK_COLUMN = "CODCAS";

    public static final Property<String> DESCAS = Property.create("descas", String.class);
    public static final Property<List<AnagraficaUfficiali>> ANAGRAFICA_UFFICIALIS = Property.create("anagraficaUfficialis", List.class);
    public static final Property<List<CodiciCasaIdentificazione>> CODICI_CASA_IDENTIFICAZIONES = Property.create("codiciCasaIdentificaziones", List.class);

    public void setDescas(String descas) {
        writeProperty("descas", descas);
    }
    public String getDescas() {
        return (String)readProperty("descas");
    }

    public void addToAnagraficaUfficialis(AnagraficaUfficiali obj) {
        addToManyTarget("anagraficaUfficialis", obj, true);
    }
    public void removeFromAnagraficaUfficialis(AnagraficaUfficiali obj) {
        removeToManyTarget("anagraficaUfficialis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AnagraficaUfficiali> getAnagraficaUfficialis() {
        return (List<AnagraficaUfficiali>)readProperty("anagraficaUfficialis");
    }


    public void addToCodiciCasaIdentificaziones(CodiciCasaIdentificazione obj) {
        addToManyTarget("codiciCasaIdentificaziones", obj, true);
    }
    public void removeFromCodiciCasaIdentificaziones(CodiciCasaIdentificazione obj) {
        removeToManyTarget("codiciCasaIdentificaziones", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CodiciCasaIdentificazione> getCodiciCasaIdentificaziones() {
        return (List<CodiciCasaIdentificazione>)readProperty("codiciCasaIdentificaziones");
    }


}
