package model.paser.anagrafiche.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.anagrafiche.custom.AnagraficaMarche;
import model.paser.anagrafiche.custom.AnagraficaModelli;
import model.paser.anagrafiche.custom.AnagraficaRaggruppamentoModelli;

/**
 * Class _CrossRaggruppamentoModelli was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CrossRaggruppamentoModelli extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODMOD_PK_COLUMN = "CODMOD";
    public static final String CODMOR_PK_COLUMN = "CODMOR";

    public static final Property<AnagraficaMarche> ANAGRAFICA_MARCHE = Property.create("anagraficaMarche", AnagraficaMarche.class);
    public static final Property<AnagraficaModelli> ANAGRAFICA_MODELLI = Property.create("anagraficaModelli", AnagraficaModelli.class);
    public static final Property<AnagraficaRaggruppamentoModelli> ANAGRAFICA_RAGGRUPPAMENTO_MODELLI = Property.create("anagraficaRaggruppamentoModelli", AnagraficaRaggruppamentoModelli.class);

    public void setAnagraficaMarche(AnagraficaMarche anagraficaMarche) {
        setToOneTarget("anagraficaMarche", anagraficaMarche, true);
    }

    public AnagraficaMarche getAnagraficaMarche() {
        return (AnagraficaMarche)readProperty("anagraficaMarche");
    }


    public void setAnagraficaModelli(AnagraficaModelli anagraficaModelli) {
        setToOneTarget("anagraficaModelli", anagraficaModelli, true);
    }

    public AnagraficaModelli getAnagraficaModelli() {
        return (AnagraficaModelli)readProperty("anagraficaModelli");
    }


    public void setAnagraficaRaggruppamentoModelli(AnagraficaRaggruppamentoModelli anagraficaRaggruppamentoModelli) {
        setToOneTarget("anagraficaRaggruppamentoModelli", anagraficaRaggruppamentoModelli, true);
    }

    public AnagraficaRaggruppamentoModelli getAnagraficaRaggruppamentoModelli() {
        return (AnagraficaRaggruppamentoModelli)readProperty("anagraficaRaggruppamentoModelli");
    }


}
