package model.paser.anagrafiche.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.identificazione.custom.DettagliNucleoMotore;

/**
 * Class _DisposizioneCilindri was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DisposizioneCilindri extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODDIS_PK_COLUMN = "CODDIS";

    public static final Property<String> DESCIL = Property.create("descil", String.class);
    public static final Property<String> DISCIL = Property.create("discil", String.class);
    public static final Property<List<DettagliNucleoMotore>> DETTAGLI_NUCLEO_MOTORES = Property.create("dettagliNucleoMotores", List.class);

    public void setDescil(String descil) {
        writeProperty("descil", descil);
    }
    public String getDescil() {
        return (String)readProperty("descil");
    }

    public void setDiscil(String discil) {
        writeProperty("discil", discil);
    }
    public String getDiscil() {
        return (String)readProperty("discil");
    }

    public void addToDettagliNucleoMotores(DettagliNucleoMotore obj) {
        addToManyTarget("dettagliNucleoMotores", obj, true);
    }
    public void removeFromDettagliNucleoMotores(DettagliNucleoMotore obj) {
        removeToManyTarget("dettagliNucleoMotores", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DettagliNucleoMotore> getDettagliNucleoMotores() {
        return (List<DettagliNucleoMotore>)readProperty("dettagliNucleoMotores");
    }


}
