package model.paser.anagrafiche.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _DispositiviAnti_inquinamento was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DispositiviAnti_inquinamento extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODCAT_PK_COLUMN = "CODCAT";

    public static final Property<String> CATALI = Property.create("catali", String.class);
    public static final Property<String> DESCAT = Property.create("descat", String.class);

    public void setCatali(String catali) {
        writeProperty("catali", catali);
    }
    public String getCatali() {
        return (String)readProperty("catali");
    }

    public void setDescat(String descat) {
        writeProperty("descat", descat);
    }
    public String getDescat() {
        return (String)readProperty("descat");
    }

}
