package model.paser.anagrafiche.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.identificazione.custom.DatiTecniciBase;

/**
 * Class _NormeAnti_inquinamento was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NormeAnti_inquinamento extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODNOR_PK_COLUMN = "CODNOR";

    public static final Property<String> DESNOR = Property.create("desnor", String.class);
    public static final Property<List<DatiTecniciBase>> DATI_TECNICI_BASES = Property.create("datiTecniciBases", List.class);

    public void setDesnor(String desnor) {
        writeProperty("desnor", desnor);
    }
    public String getDesnor() {
        return (String)readProperty("desnor");
    }

    public void addToDatiTecniciBases(DatiTecniciBase obj) {
        addToManyTarget("datiTecniciBases", obj, true);
    }
    public void removeFromDatiTecniciBases(DatiTecniciBase obj) {
        removeToManyTarget("datiTecniciBases", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DatiTecniciBase> getDatiTecniciBases() {
        return (List<DatiTecniciBase>)readProperty("datiTecniciBases");
    }


}
