package model.paser.anagrafiche.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Sovralimentazione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Sovralimentazione extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODSOV_PK_COLUMN = "CODSOV";

    public static final Property<String> DESSOV = Property.create("dessov", String.class);
    public static final Property<String> TURBOX = Property.create("turbox", String.class);

    public void setDessov(String dessov) {
        writeProperty("dessov", dessov);
    }
    public String getDessov() {
        return (String)readProperty("dessov");
    }

    public void setTurbox(String turbox) {
        writeProperty("turbox", turbox);
    }
    public String getTurbox() {
        return (String)readProperty("turbox");
    }

}
