package model.paser.anagrafiche.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _TipoIbridizzazione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TipoIbridizzazione extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODIBR_PK_COLUMN = "CODIBR";

    public static final Property<String> DESIBR = Property.create("desibr", String.class);

    public void setDesibr(String desibr) {
        writeProperty("desibr", desibr);
    }
    public String getDesibr() {
        return (String)readProperty("desibr");
    }

}
