package model.paser.anagrafiche.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _TipoVariazione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TipoVariazione extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODCAU_PK_COLUMN = "CODCAU";

    public static final Property<String> DESCAU = Property.create("descau", String.class);
    public static final Property<String> TIPCAU = Property.create("tipcau", String.class);

    public void setDescau(String descau) {
        writeProperty("descau", descau);
    }
    public String getDescau() {
        return (String)readProperty("descau");
    }

    public void setTipcau(String tipcau) {
        writeProperty("tipcau", tipcau);
    }
    public String getTipcau() {
        return (String)readProperty("tipcau");
    }

}
