package model.paser.anagrafiche.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.identificazione.custom.DettagliNucleoMotore;

/**
 * Class _TipoCombustibile was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TipoCombustibile extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODCOM_PK_COLUMN = "CODCOM";

    public static final Property<String> CODCO1 = Property.create("codco1", String.class);
    public static final Property<String> CODCO2 = Property.create("codco2", String.class);
    public static final Property<String> CODCO3 = Property.create("codco3", String.class);
    public static final Property<String> DESCOM = Property.create("descom", String.class);
    public static final Property<String> TIPCOM = Property.create("tipcom", String.class);
    public static final Property<List<DettagliNucleoMotore>> DETTAGLI_NUCLEO_MOTORES = Property.create("dettagliNucleoMotores", List.class);

    public void setCodco1(String codco1) {
        writeProperty("codco1", codco1);
    }
    public String getCodco1() {
        return (String)readProperty("codco1");
    }

    public void setCodco2(String codco2) {
        writeProperty("codco2", codco2);
    }
    public String getCodco2() {
        return (String)readProperty("codco2");
    }

    public void setCodco3(String codco3) {
        writeProperty("codco3", codco3);
    }
    public String getCodco3() {
        return (String)readProperty("codco3");
    }

    public void setDescom(String descom) {
        writeProperty("descom", descom);
    }
    public String getDescom() {
        return (String)readProperty("descom");
    }

    public void setTipcom(String tipcom) {
        writeProperty("tipcom", tipcom);
    }
    public String getTipcom() {
        return (String)readProperty("tipcom");
    }

    public void addToDettagliNucleoMotores(DettagliNucleoMotore obj) {
        addToManyTarget("dettagliNucleoMotores", obj, true);
    }
    public void removeFromDettagliNucleoMotores(DettagliNucleoMotore obj) {
        removeToManyTarget("dettagliNucleoMotores", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DettagliNucleoMotore> getDettagliNucleoMotores() {
        return (List<DettagliNucleoMotore>)readProperty("dettagliNucleoMotores");
    }


}
