package model.paser.anagrafiche.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.identificazione.custom.DatiTecniciBase;

/**
 * Class _TipoCarrozzeria was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TipoCarrozzeria extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODCAR_PK_COLUMN = "CODCAR";

    public static final Property<String> DESCAR = Property.create("descar", String.class);
    public static final Property<String> TIPCAR = Property.create("tipcar", String.class);
    public static final Property<List<DatiTecniciBase>> DATI_TECNICI_BASES = Property.create("datiTecniciBases", List.class);

    public void setDescar(String descar) {
        writeProperty("descar", descar);
    }
    public String getDescar() {
        return (String)readProperty("descar");
    }

    public void setTipcar(String tipcar) {
        writeProperty("tipcar", tipcar);
    }
    public String getTipcar() {
        return (String)readProperty("tipcar");
    }

    public void addToDatiTecniciBases(DatiTecniciBase obj) {
        addToManyTarget("datiTecniciBases", obj, true);
    }
    public void removeFromDatiTecniciBases(DatiTecniciBase obj) {
        removeToManyTarget("datiTecniciBases", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DatiTecniciBase> getDatiTecniciBases() {
        return (List<DatiTecniciBase>)readProperty("datiTecniciBases");
    }


}
