package model.paser.anagrafiche.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _TipoTrazione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TipoTrazione extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODTRA_PK_COLUMN = "CODTRA";

    public static final Property<String> DESTRA = Property.create("destra", String.class);
    public static final Property<String> TRAZIO = Property.create("trazio", String.class);

    public void setDestra(String destra) {
        writeProperty("destra", destra);
    }
    public String getDestra() {
        return (String)readProperty("destra");
    }

    public void setTrazio(String trazio) {
        writeProperty("trazio", trazio);
    }
    public String getTrazio() {
        return (String)readProperty("trazio");
    }

}
