package model.paser.anagrafiche.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.identificazione.custom.Pneumatici;

/**
 * Class _TipoPneumatici was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TipoPneumatici extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODTPN_PK_COLUMN = "CODTPN";

    public static final Property<String> DESTPN = Property.create("destpn", String.class);
    public static final Property<Boolean> FLGINV = Property.create("flginv", Boolean.class);
    public static final Property<String> FLGSTR = Property.create("flgstr", String.class);
    public static final Property<List<Pneumatici>> PNEUMATICIS = Property.create("pneumaticis", List.class);

    public void setDestpn(String destpn) {
        writeProperty("destpn", destpn);
    }
    public String getDestpn() {
        return (String)readProperty("destpn");
    }

    public void setFlginv(boolean flginv) {
        writeProperty("flginv", flginv);
    }
	public boolean isFlginv() {
        Boolean value = (Boolean)readProperty("flginv");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setFlgstr(String flgstr) {
        writeProperty("flgstr", flgstr);
    }
    public String getFlgstr() {
        return (String)readProperty("flgstr");
    }

    public void addToPneumaticis(Pneumatici obj) {
        addToManyTarget("pneumaticis", obj, true);
    }
    public void removeFromPneumaticis(Pneumatici obj) {
        removeToManyTarget("pneumaticis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Pneumatici> getPneumaticis() {
        return (List<Pneumatici>)readProperty("pneumaticis");
    }


}
