package model.paser.anagrafiche.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _TipoCambio was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TipoCambio extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODCAM_PK_COLUMN = "CODCAM";

    public static final Property<String> CAMBIO = Property.create("cambio", String.class);

    public void setCambio(String cambio) {
        writeProperty("cambio", cambio);
    }
    public String getCambio() {
        return (String)readProperty("cambio");
    }

}
