package model.paser.anagrafiche.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.identificazione.custom.Foto;

/**
 * Class _VistaFoto was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VistaFoto extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String VISFOT_PK_COLUMN = "VISFOT";

    public static final Property<String> DESVIS = Property.create("desvis", String.class);
    public static final Property<List<Foto>> FOTOES = Property.create("fotoes", List.class);

    public void setDesvis(String desvis) {
        writeProperty("desvis", desvis);
    }
    public String getDesvis() {
        return (String)readProperty("desvis");
    }

    public void addToFotoes(Foto obj) {
        addToManyTarget("fotoes", obj, true);
    }
    public void removeFromFotoes(Foto obj) {
        removeToManyTarget("fotoes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Foto> getFotoes() {
        return (List<Foto>)readProperty("fotoes");
    }


}
