package model.paser.identificazione.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.anagrafiche.custom.AnagraficaAllestimenti;
import model.paser.anagrafiche.custom.CategoriaVeicolo;
import model.paser.equipaggiamenti.custom.Esclusioni;
import model.paser.equipaggiamenti.custom.Inclusioni;
import model.paser.equipaggiamenti.custom.ListiniUfficiali;
import model.paser.equipaggiamenti.custom.Vincoli;
import model.paser.identificazione.custom.CambiEPrestazioni;
import model.paser.identificazione.custom.CauseAnnoMese;
import model.paser.identificazione.custom.CodiciCasaIdentificazione;
import model.paser.identificazione.custom.DatiTecniciBase;
import model.paser.identificazione.custom.DatiTecniciSpecificiPerIbridi;
import model.paser.identificazione.custom.DettaglioSegmenti;
import model.paser.identificazione.custom.Foto;
import model.paser.identificazione.custom.InformazioniAggiuntive;
import model.paser.identificazione.custom.ListiniNuovo;
import model.paser.identificazione.custom.Pneumatici;
import model.paser.identificazione.custom.RiferimentiInfocarEliminati;
import model.paser.usato.custom.CrossRcl;
import model.paser.usato.custom.InformazioniAggiuntiveUsato;
import model.paser.usato.custom.Quotazioni;

/**
 * Class _Base was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Base extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANNOXX_PK_COLUMN = "ANNOXX";
    public static final String CODALL_PK_COLUMN = "CODALL";
    public static final String MESEXX_PK_COLUMN = "MESEXX";

    public static final Property<Integer> ANNOUF = Property.create("annouf", Integer.class);
    public static final Property<Integer> ANNOX2 = Property.create("annox2", Integer.class);
    public static final Property<Integer> CODAPR = Property.create("codapr", Integer.class);
    public static final Property<Integer> CODMPR = Property.create("codmpr", Integer.class);
    public static final Property<String> FINIMM = Property.create("finimm", String.class);
    public static final Property<String> FINVEN = Property.create("finven", String.class);
    public static final Property<String> INIIMM = Property.create("iniimm", String.class);
    public static final Property<String> INIVEN = Property.create("iniven", String.class);
    public static final Property<Integer> MESEUF = Property.create("meseuf", Integer.class);
    public static final Property<Integer> MESEX2 = Property.create("mesex2", Integer.class);
    public static final Property<List<AnagraficaAllestimenti>> ANAGRAFICA_ALLESTIMENTIS = Property.create("anagraficaAllestimentis", List.class);
    public static final Property<List<CambiEPrestazioni>> CAMBI_EPRESTAZIONIS = Property.create("cambiEPrestazionis", List.class);
    public static final Property<List<CambiEPrestazioni>> CAMBI_EPRESTAZIONIS1 = Property.create("cambiEPrestazionis1", List.class);
    public static final Property<List<CambiEPrestazioni>> CAMBI_EPRESTAZIONIS2 = Property.create("cambiEPrestazionis2", List.class);
    public static final Property<CategoriaVeicolo> CATEGORIA_VEICOLO = Property.create("categoriaVeicolo", CategoriaVeicolo.class);
    public static final Property<List<CauseAnnoMese>> CAUSE_ANNO_MESE = Property.create("causeAnnoMese", List.class);
    public static final Property<List<CauseAnnoMese>> CAUSE_ANNO_MESE1 = Property.create("causeAnnoMese1", List.class);
    public static final Property<List<CauseAnnoMese>> CAUSE_ANNO_MESE2 = Property.create("causeAnnoMese2", List.class);
    public static final Property<List<CodiciCasaIdentificazione>> CODICI_CASA_IDENTIFICAZIONES = Property.create("codiciCasaIdentificaziones", List.class);
    public static final Property<List<CodiciCasaIdentificazione>> CODICI_CASA_IDENTIFICAZIONES1 = Property.create("codiciCasaIdentificaziones1", List.class);
    public static final Property<List<CodiciCasaIdentificazione>> CODICI_CASA_IDENTIFICAZIONES2 = Property.create("codiciCasaIdentificaziones2", List.class);
    public static final Property<List<CrossRcl>> CROSS_RCLS = Property.create("crossRcls", List.class);
    public static final Property<List<CrossRcl>> CROSS_RCLS1 = Property.create("crossRcls1", List.class);
    public static final Property<List<CrossRcl>> CROSS_RCLS2 = Property.create("crossRcls2", List.class);
    public static final Property<List<DatiTecniciBase>> DATI_TECNICI_BASES = Property.create("datiTecniciBases", List.class);
    public static final Property<List<DatiTecniciBase>> DATI_TECNICI_BASES1 = Property.create("datiTecniciBases1", List.class);
    public static final Property<List<DatiTecniciBase>> DATI_TECNICI_BASES2 = Property.create("datiTecniciBases2", List.class);
    public static final Property<List<DatiTecniciSpecificiPerIbridi>> DATI_TECNICI_SPECIFICI_PER_IBRIDIS = Property.create("datiTecniciSpecificiPerIbridis", List.class);
    public static final Property<List<DatiTecniciSpecificiPerIbridi>> DATI_TECNICI_SPECIFICI_PER_IBRIDIS1 = Property.create("datiTecniciSpecificiPerIbridis1", List.class);
    public static final Property<List<DatiTecniciSpecificiPerIbridi>> DATI_TECNICI_SPECIFICI_PER_IBRIDIS2 = Property.create("datiTecniciSpecificiPerIbridis2", List.class);
    public static final Property<DettaglioSegmenti> DETTAGLIO_SEGMENTI = Property.create("dettaglioSegmenti", DettaglioSegmenti.class);
    public static final Property<List<Esclusioni>> ESCLUSIONIS = Property.create("esclusionis", List.class);
    public static final Property<List<Esclusioni>> ESCLUSIONIS1 = Property.create("esclusionis1", List.class);
    public static final Property<List<Esclusioni>> ESCLUSIONIS2 = Property.create("esclusionis2", List.class);
    public static final Property<List<Foto>> FOTOES = Property.create("fotoes", List.class);
    public static final Property<List<Foto>> FOTOES1 = Property.create("fotoes1", List.class);
    public static final Property<List<Foto>> FOTOES2 = Property.create("fotoes2", List.class);
    public static final Property<List<Inclusioni>> INCLUSIONIS = Property.create("inclusionis", List.class);
    public static final Property<List<Inclusioni>> INCLUSIONIS1 = Property.create("inclusionis1", List.class);
    public static final Property<List<Inclusioni>> INCLUSIONIS2 = Property.create("inclusionis2", List.class);
    public static final Property<List<InformazioniAggiuntiveUsato>> INFORMAZIONI_AGGIUNTIVE_USATOES = Property.create("informazioniAggiuntiveUsatoes", List.class);
    public static final Property<List<InformazioniAggiuntiveUsato>> INFORMAZIONI_AGGIUNTIVE_USATOES1 = Property.create("informazioniAggiuntiveUsatoes1", List.class);
    public static final Property<List<InformazioniAggiuntiveUsato>> INFORMAZIONI_AGGIUNTIVE_USATOES2 = Property.create("informazioniAggiuntiveUsatoes2", List.class);
    public static final Property<List<InformazioniAggiuntive>> INFORMAZIONI_AGGIUNTIVES = Property.create("informazioniAggiuntives", List.class);
    public static final Property<List<InformazioniAggiuntive>> INFORMAZIONI_AGGIUNTIVES1 = Property.create("informazioniAggiuntives1", List.class);
    public static final Property<List<InformazioniAggiuntive>> INFORMAZIONI_AGGIUNTIVES2 = Property.create("informazioniAggiuntives2", List.class);
    public static final Property<List<ListiniNuovo>> LISTINI_NUOVOES = Property.create("listiniNuovoes", List.class);
    public static final Property<List<ListiniNuovo>> LISTINI_NUOVOES1 = Property.create("listiniNuovoes1", List.class);
    public static final Property<List<ListiniNuovo>> LISTINI_NUOVOES2 = Property.create("listiniNuovoes2", List.class);
    public static final Property<List<ListiniUfficiali>> LISTINI_UFFICIALIS = Property.create("listiniUfficialis", List.class);
    public static final Property<List<ListiniUfficiali>> LISTINI_UFFICIALIS1 = Property.create("listiniUfficialis1", List.class);
    public static final Property<List<ListiniUfficiali>> LISTINI_UFFICIALIS2 = Property.create("listiniUfficialis2", List.class);
    public static final Property<List<Pneumatici>> PNEUMATICIS = Property.create("pneumaticis", List.class);
    public static final Property<List<Pneumatici>> PNEUMATICIS1 = Property.create("pneumaticis1", List.class);
    public static final Property<List<Pneumatici>> PNEUMATICIS2 = Property.create("pneumaticis2", List.class);
    public static final Property<List<Quotazioni>> QUOTAZIONIS = Property.create("quotazionis", List.class);
    public static final Property<List<Quotazioni>> QUOTAZIONIS1 = Property.create("quotazionis1", List.class);
    public static final Property<List<Quotazioni>> QUOTAZIONIS2 = Property.create("quotazionis2", List.class);
    public static final Property<List<RiferimentiInfocarEliminati>> RIFERIMENTI_INFOCAR_ELIMINATIS = Property.create("riferimentiInfocarEliminatis", List.class);
    public static final Property<List<RiferimentiInfocarEliminati>> RIFERIMENTI_INFOCAR_ELIMINATIS1 = Property.create("riferimentiInfocarEliminatis1", List.class);
    public static final Property<List<RiferimentiInfocarEliminati>> RIFERIMENTI_INFOCAR_ELIMINATIS2 = Property.create("riferimentiInfocarEliminatis2", List.class);
    public static final Property<List<Vincoli>> VINCOLIS = Property.create("vincolis", List.class);
    public static final Property<List<Vincoli>> VINCOLIS1 = Property.create("vincolis1", List.class);
    public static final Property<List<Vincoli>> VINCOLIS2 = Property.create("vincolis2", List.class);

    public void setAnnouf(int annouf) {
        writeProperty("annouf", annouf);
    }
    public int getAnnouf() {
        Object value = readProperty("annouf");
        return (value != null) ? (Integer) value : 0;
    }

    public void setAnnox2(int annox2) {
        writeProperty("annox2", annox2);
    }
    public int getAnnox2() {
        Object value = readProperty("annox2");
        return (value != null) ? (Integer) value : 0;
    }

    public void setCodapr(int codapr) {
        writeProperty("codapr", codapr);
    }
    public int getCodapr() {
        Object value = readProperty("codapr");
        return (value != null) ? (Integer) value : 0;
    }

    public void setCodmpr(int codmpr) {
        writeProperty("codmpr", codmpr);
    }
    public int getCodmpr() {
        Object value = readProperty("codmpr");
        return (value != null) ? (Integer) value : 0;
    }

    public void setFinimm(String finimm) {
        writeProperty("finimm", finimm);
    }
    public String getFinimm() {
        return (String)readProperty("finimm");
    }

    public void setFinven(String finven) {
        writeProperty("finven", finven);
    }
    public String getFinven() {
        return (String)readProperty("finven");
    }

    public void setIniimm(String iniimm) {
        writeProperty("iniimm", iniimm);
    }
    public String getIniimm() {
        return (String)readProperty("iniimm");
    }

    public void setIniven(String iniven) {
        writeProperty("iniven", iniven);
    }
    public String getIniven() {
        return (String)readProperty("iniven");
    }

    public void setMeseuf(int meseuf) {
        writeProperty("meseuf", meseuf);
    }
    public int getMeseuf() {
        Object value = readProperty("meseuf");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMesex2(int mesex2) {
        writeProperty("mesex2", mesex2);
    }
    public int getMesex2() {
        Object value = readProperty("mesex2");
        return (value != null) ? (Integer) value : 0;
    }

    public void addToAnagraficaAllestimentis(AnagraficaAllestimenti obj) {
        addToManyTarget("anagraficaAllestimentis", obj, true);
    }
    public void removeFromAnagraficaAllestimentis(AnagraficaAllestimenti obj) {
        removeToManyTarget("anagraficaAllestimentis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AnagraficaAllestimenti> getAnagraficaAllestimentis() {
        return (List<AnagraficaAllestimenti>)readProperty("anagraficaAllestimentis");
    }


    public void addToCambiEPrestazionis(CambiEPrestazioni obj) {
        addToManyTarget("cambiEPrestazionis", obj, true);
    }
    public void removeFromCambiEPrestazionis(CambiEPrestazioni obj) {
        removeToManyTarget("cambiEPrestazionis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CambiEPrestazioni> getCambiEPrestazionis() {
        return (List<CambiEPrestazioni>)readProperty("cambiEPrestazionis");
    }


    public void addToCambiEPrestazionis1(CambiEPrestazioni obj) {
        addToManyTarget("cambiEPrestazionis1", obj, true);
    }
    public void removeFromCambiEPrestazionis1(CambiEPrestazioni obj) {
        removeToManyTarget("cambiEPrestazionis1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CambiEPrestazioni> getCambiEPrestazionis1() {
        return (List<CambiEPrestazioni>)readProperty("cambiEPrestazionis1");
    }


    public void addToCambiEPrestazionis2(CambiEPrestazioni obj) {
        addToManyTarget("cambiEPrestazionis2", obj, true);
    }
    public void removeFromCambiEPrestazionis2(CambiEPrestazioni obj) {
        removeToManyTarget("cambiEPrestazionis2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CambiEPrestazioni> getCambiEPrestazionis2() {
        return (List<CambiEPrestazioni>)readProperty("cambiEPrestazionis2");
    }


    public void setCategoriaVeicolo(CategoriaVeicolo categoriaVeicolo) {
        setToOneTarget("categoriaVeicolo", categoriaVeicolo, true);
    }

    public CategoriaVeicolo getCategoriaVeicolo() {
        return (CategoriaVeicolo)readProperty("categoriaVeicolo");
    }


    public void addToCauseAnnoMese(CauseAnnoMese obj) {
        addToManyTarget("causeAnnoMese", obj, true);
    }
    public void removeFromCauseAnnoMese(CauseAnnoMese obj) {
        removeToManyTarget("causeAnnoMese", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CauseAnnoMese> getCauseAnnoMese() {
        return (List<CauseAnnoMese>)readProperty("causeAnnoMese");
    }


    public void addToCauseAnnoMese1(CauseAnnoMese obj) {
        addToManyTarget("causeAnnoMese1", obj, true);
    }
    public void removeFromCauseAnnoMese1(CauseAnnoMese obj) {
        removeToManyTarget("causeAnnoMese1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CauseAnnoMese> getCauseAnnoMese1() {
        return (List<CauseAnnoMese>)readProperty("causeAnnoMese1");
    }


    public void addToCauseAnnoMese2(CauseAnnoMese obj) {
        addToManyTarget("causeAnnoMese2", obj, true);
    }
    public void removeFromCauseAnnoMese2(CauseAnnoMese obj) {
        removeToManyTarget("causeAnnoMese2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CauseAnnoMese> getCauseAnnoMese2() {
        return (List<CauseAnnoMese>)readProperty("causeAnnoMese2");
    }


    public void addToCodiciCasaIdentificaziones(CodiciCasaIdentificazione obj) {
        addToManyTarget("codiciCasaIdentificaziones", obj, true);
    }
    public void removeFromCodiciCasaIdentificaziones(CodiciCasaIdentificazione obj) {
        removeToManyTarget("codiciCasaIdentificaziones", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CodiciCasaIdentificazione> getCodiciCasaIdentificaziones() {
        return (List<CodiciCasaIdentificazione>)readProperty("codiciCasaIdentificaziones");
    }


    public void addToCodiciCasaIdentificaziones1(CodiciCasaIdentificazione obj) {
        addToManyTarget("codiciCasaIdentificaziones1", obj, true);
    }
    public void removeFromCodiciCasaIdentificaziones1(CodiciCasaIdentificazione obj) {
        removeToManyTarget("codiciCasaIdentificaziones1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CodiciCasaIdentificazione> getCodiciCasaIdentificaziones1() {
        return (List<CodiciCasaIdentificazione>)readProperty("codiciCasaIdentificaziones1");
    }


    public void addToCodiciCasaIdentificaziones2(CodiciCasaIdentificazione obj) {
        addToManyTarget("codiciCasaIdentificaziones2", obj, true);
    }
    public void removeFromCodiciCasaIdentificaziones2(CodiciCasaIdentificazione obj) {
        removeToManyTarget("codiciCasaIdentificaziones2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CodiciCasaIdentificazione> getCodiciCasaIdentificaziones2() {
        return (List<CodiciCasaIdentificazione>)readProperty("codiciCasaIdentificaziones2");
    }


    public void addToCrossRcls(CrossRcl obj) {
        addToManyTarget("crossRcls", obj, true);
    }
    public void removeFromCrossRcls(CrossRcl obj) {
        removeToManyTarget("crossRcls", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CrossRcl> getCrossRcls() {
        return (List<CrossRcl>)readProperty("crossRcls");
    }


    public void addToCrossRcls1(CrossRcl obj) {
        addToManyTarget("crossRcls1", obj, true);
    }
    public void removeFromCrossRcls1(CrossRcl obj) {
        removeToManyTarget("crossRcls1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CrossRcl> getCrossRcls1() {
        return (List<CrossRcl>)readProperty("crossRcls1");
    }


    public void addToCrossRcls2(CrossRcl obj) {
        addToManyTarget("crossRcls2", obj, true);
    }
    public void removeFromCrossRcls2(CrossRcl obj) {
        removeToManyTarget("crossRcls2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CrossRcl> getCrossRcls2() {
        return (List<CrossRcl>)readProperty("crossRcls2");
    }


    public void addToDatiTecniciBases(DatiTecniciBase obj) {
        addToManyTarget("datiTecniciBases", obj, true);
    }
    public void removeFromDatiTecniciBases(DatiTecniciBase obj) {
        removeToManyTarget("datiTecniciBases", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DatiTecniciBase> getDatiTecniciBases() {
        return (List<DatiTecniciBase>)readProperty("datiTecniciBases");
    }


    public void addToDatiTecniciBases1(DatiTecniciBase obj) {
        addToManyTarget("datiTecniciBases1", obj, true);
    }
    public void removeFromDatiTecniciBases1(DatiTecniciBase obj) {
        removeToManyTarget("datiTecniciBases1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DatiTecniciBase> getDatiTecniciBases1() {
        return (List<DatiTecniciBase>)readProperty("datiTecniciBases1");
    }


    public void addToDatiTecniciBases2(DatiTecniciBase obj) {
        addToManyTarget("datiTecniciBases2", obj, true);
    }
    public void removeFromDatiTecniciBases2(DatiTecniciBase obj) {
        removeToManyTarget("datiTecniciBases2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DatiTecniciBase> getDatiTecniciBases2() {
        return (List<DatiTecniciBase>)readProperty("datiTecniciBases2");
    }


    public void addToDatiTecniciSpecificiPerIbridis(DatiTecniciSpecificiPerIbridi obj) {
        addToManyTarget("datiTecniciSpecificiPerIbridis", obj, true);
    }
    public void removeFromDatiTecniciSpecificiPerIbridis(DatiTecniciSpecificiPerIbridi obj) {
        removeToManyTarget("datiTecniciSpecificiPerIbridis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DatiTecniciSpecificiPerIbridi> getDatiTecniciSpecificiPerIbridis() {
        return (List<DatiTecniciSpecificiPerIbridi>)readProperty("datiTecniciSpecificiPerIbridis");
    }


    public void addToDatiTecniciSpecificiPerIbridis1(DatiTecniciSpecificiPerIbridi obj) {
        addToManyTarget("datiTecniciSpecificiPerIbridis1", obj, true);
    }
    public void removeFromDatiTecniciSpecificiPerIbridis1(DatiTecniciSpecificiPerIbridi obj) {
        removeToManyTarget("datiTecniciSpecificiPerIbridis1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DatiTecniciSpecificiPerIbridi> getDatiTecniciSpecificiPerIbridis1() {
        return (List<DatiTecniciSpecificiPerIbridi>)readProperty("datiTecniciSpecificiPerIbridis1");
    }


    public void addToDatiTecniciSpecificiPerIbridis2(DatiTecniciSpecificiPerIbridi obj) {
        addToManyTarget("datiTecniciSpecificiPerIbridis2", obj, true);
    }
    public void removeFromDatiTecniciSpecificiPerIbridis2(DatiTecniciSpecificiPerIbridi obj) {
        removeToManyTarget("datiTecniciSpecificiPerIbridis2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DatiTecniciSpecificiPerIbridi> getDatiTecniciSpecificiPerIbridis2() {
        return (List<DatiTecniciSpecificiPerIbridi>)readProperty("datiTecniciSpecificiPerIbridis2");
    }


    public void setDettaglioSegmenti(DettaglioSegmenti dettaglioSegmenti) {
        setToOneTarget("dettaglioSegmenti", dettaglioSegmenti, true);
    }

    public DettaglioSegmenti getDettaglioSegmenti() {
        return (DettaglioSegmenti)readProperty("dettaglioSegmenti");
    }


    public void addToEsclusionis(Esclusioni obj) {
        addToManyTarget("esclusionis", obj, true);
    }
    public void removeFromEsclusionis(Esclusioni obj) {
        removeToManyTarget("esclusionis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Esclusioni> getEsclusionis() {
        return (List<Esclusioni>)readProperty("esclusionis");
    }


    public void addToEsclusionis1(Esclusioni obj) {
        addToManyTarget("esclusionis1", obj, true);
    }
    public void removeFromEsclusionis1(Esclusioni obj) {
        removeToManyTarget("esclusionis1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Esclusioni> getEsclusionis1() {
        return (List<Esclusioni>)readProperty("esclusionis1");
    }


    public void addToEsclusionis2(Esclusioni obj) {
        addToManyTarget("esclusionis2", obj, true);
    }
    public void removeFromEsclusionis2(Esclusioni obj) {
        removeToManyTarget("esclusionis2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Esclusioni> getEsclusionis2() {
        return (List<Esclusioni>)readProperty("esclusionis2");
    }


    public void addToFotoes(Foto obj) {
        addToManyTarget("fotoes", obj, true);
    }
    public void removeFromFotoes(Foto obj) {
        removeToManyTarget("fotoes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Foto> getFotoes() {
        return (List<Foto>)readProperty("fotoes");
    }


    public void addToFotoes1(Foto obj) {
        addToManyTarget("fotoes1", obj, true);
    }
    public void removeFromFotoes1(Foto obj) {
        removeToManyTarget("fotoes1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Foto> getFotoes1() {
        return (List<Foto>)readProperty("fotoes1");
    }


    public void addToFotoes2(Foto obj) {
        addToManyTarget("fotoes2", obj, true);
    }
    public void removeFromFotoes2(Foto obj) {
        removeToManyTarget("fotoes2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Foto> getFotoes2() {
        return (List<Foto>)readProperty("fotoes2");
    }


    public void addToInclusionis(Inclusioni obj) {
        addToManyTarget("inclusionis", obj, true);
    }
    public void removeFromInclusionis(Inclusioni obj) {
        removeToManyTarget("inclusionis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Inclusioni> getInclusionis() {
        return (List<Inclusioni>)readProperty("inclusionis");
    }


    public void addToInclusionis1(Inclusioni obj) {
        addToManyTarget("inclusionis1", obj, true);
    }
    public void removeFromInclusionis1(Inclusioni obj) {
        removeToManyTarget("inclusionis1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Inclusioni> getInclusionis1() {
        return (List<Inclusioni>)readProperty("inclusionis1");
    }


    public void addToInclusionis2(Inclusioni obj) {
        addToManyTarget("inclusionis2", obj, true);
    }
    public void removeFromInclusionis2(Inclusioni obj) {
        removeToManyTarget("inclusionis2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Inclusioni> getInclusionis2() {
        return (List<Inclusioni>)readProperty("inclusionis2");
    }


    public void addToInformazioniAggiuntiveUsatoes(InformazioniAggiuntiveUsato obj) {
        addToManyTarget("informazioniAggiuntiveUsatoes", obj, true);
    }
    public void removeFromInformazioniAggiuntiveUsatoes(InformazioniAggiuntiveUsato obj) {
        removeToManyTarget("informazioniAggiuntiveUsatoes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InformazioniAggiuntiveUsato> getInformazioniAggiuntiveUsatoes() {
        return (List<InformazioniAggiuntiveUsato>)readProperty("informazioniAggiuntiveUsatoes");
    }


    public void addToInformazioniAggiuntiveUsatoes1(InformazioniAggiuntiveUsato obj) {
        addToManyTarget("informazioniAggiuntiveUsatoes1", obj, true);
    }
    public void removeFromInformazioniAggiuntiveUsatoes1(InformazioniAggiuntiveUsato obj) {
        removeToManyTarget("informazioniAggiuntiveUsatoes1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InformazioniAggiuntiveUsato> getInformazioniAggiuntiveUsatoes1() {
        return (List<InformazioniAggiuntiveUsato>)readProperty("informazioniAggiuntiveUsatoes1");
    }


    public void addToInformazioniAggiuntiveUsatoes2(InformazioniAggiuntiveUsato obj) {
        addToManyTarget("informazioniAggiuntiveUsatoes2", obj, true);
    }
    public void removeFromInformazioniAggiuntiveUsatoes2(InformazioniAggiuntiveUsato obj) {
        removeToManyTarget("informazioniAggiuntiveUsatoes2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InformazioniAggiuntiveUsato> getInformazioniAggiuntiveUsatoes2() {
        return (List<InformazioniAggiuntiveUsato>)readProperty("informazioniAggiuntiveUsatoes2");
    }


    public void addToInformazioniAggiuntives(InformazioniAggiuntive obj) {
        addToManyTarget("informazioniAggiuntives", obj, true);
    }
    public void removeFromInformazioniAggiuntives(InformazioniAggiuntive obj) {
        removeToManyTarget("informazioniAggiuntives", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InformazioniAggiuntive> getInformazioniAggiuntives() {
        return (List<InformazioniAggiuntive>)readProperty("informazioniAggiuntives");
    }


    public void addToInformazioniAggiuntives1(InformazioniAggiuntive obj) {
        addToManyTarget("informazioniAggiuntives1", obj, true);
    }
    public void removeFromInformazioniAggiuntives1(InformazioniAggiuntive obj) {
        removeToManyTarget("informazioniAggiuntives1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InformazioniAggiuntive> getInformazioniAggiuntives1() {
        return (List<InformazioniAggiuntive>)readProperty("informazioniAggiuntives1");
    }


    public void addToInformazioniAggiuntives2(InformazioniAggiuntive obj) {
        addToManyTarget("informazioniAggiuntives2", obj, true);
    }
    public void removeFromInformazioniAggiuntives2(InformazioniAggiuntive obj) {
        removeToManyTarget("informazioniAggiuntives2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InformazioniAggiuntive> getInformazioniAggiuntives2() {
        return (List<InformazioniAggiuntive>)readProperty("informazioniAggiuntives2");
    }


    public void addToListiniNuovoes(ListiniNuovo obj) {
        addToManyTarget("listiniNuovoes", obj, true);
    }
    public void removeFromListiniNuovoes(ListiniNuovo obj) {
        removeToManyTarget("listiniNuovoes", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ListiniNuovo> getListiniNuovoes() {
        return (List<ListiniNuovo>)readProperty("listiniNuovoes");
    }


    public void addToListiniNuovoes1(ListiniNuovo obj) {
        addToManyTarget("listiniNuovoes1", obj, true);
    }
    public void removeFromListiniNuovoes1(ListiniNuovo obj) {
        removeToManyTarget("listiniNuovoes1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ListiniNuovo> getListiniNuovoes1() {
        return (List<ListiniNuovo>)readProperty("listiniNuovoes1");
    }


    public void addToListiniNuovoes2(ListiniNuovo obj) {
        addToManyTarget("listiniNuovoes2", obj, true);
    }
    public void removeFromListiniNuovoes2(ListiniNuovo obj) {
        removeToManyTarget("listiniNuovoes2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ListiniNuovo> getListiniNuovoes2() {
        return (List<ListiniNuovo>)readProperty("listiniNuovoes2");
    }


    public void addToListiniUfficialis(ListiniUfficiali obj) {
        addToManyTarget("listiniUfficialis", obj, true);
    }
    public void removeFromListiniUfficialis(ListiniUfficiali obj) {
        removeToManyTarget("listiniUfficialis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ListiniUfficiali> getListiniUfficialis() {
        return (List<ListiniUfficiali>)readProperty("listiniUfficialis");
    }


    public void addToListiniUfficialis1(ListiniUfficiali obj) {
        addToManyTarget("listiniUfficialis1", obj, true);
    }
    public void removeFromListiniUfficialis1(ListiniUfficiali obj) {
        removeToManyTarget("listiniUfficialis1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ListiniUfficiali> getListiniUfficialis1() {
        return (List<ListiniUfficiali>)readProperty("listiniUfficialis1");
    }


    public void addToListiniUfficialis2(ListiniUfficiali obj) {
        addToManyTarget("listiniUfficialis2", obj, true);
    }
    public void removeFromListiniUfficialis2(ListiniUfficiali obj) {
        removeToManyTarget("listiniUfficialis2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ListiniUfficiali> getListiniUfficialis2() {
        return (List<ListiniUfficiali>)readProperty("listiniUfficialis2");
    }


    public void addToPneumaticis(Pneumatici obj) {
        addToManyTarget("pneumaticis", obj, true);
    }
    public void removeFromPneumaticis(Pneumatici obj) {
        removeToManyTarget("pneumaticis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Pneumatici> getPneumaticis() {
        return (List<Pneumatici>)readProperty("pneumaticis");
    }


    public void addToPneumaticis1(Pneumatici obj) {
        addToManyTarget("pneumaticis1", obj, true);
    }
    public void removeFromPneumaticis1(Pneumatici obj) {
        removeToManyTarget("pneumaticis1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Pneumatici> getPneumaticis1() {
        return (List<Pneumatici>)readProperty("pneumaticis1");
    }


    public void addToPneumaticis2(Pneumatici obj) {
        addToManyTarget("pneumaticis2", obj, true);
    }
    public void removeFromPneumaticis2(Pneumatici obj) {
        removeToManyTarget("pneumaticis2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Pneumatici> getPneumaticis2() {
        return (List<Pneumatici>)readProperty("pneumaticis2");
    }


    public void addToQuotazionis(Quotazioni obj) {
        addToManyTarget("quotazionis", obj, true);
    }
    public void removeFromQuotazionis(Quotazioni obj) {
        removeToManyTarget("quotazionis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Quotazioni> getQuotazionis() {
        return (List<Quotazioni>)readProperty("quotazionis");
    }


    public void addToQuotazionis1(Quotazioni obj) {
        addToManyTarget("quotazionis1", obj, true);
    }
    public void removeFromQuotazionis1(Quotazioni obj) {
        removeToManyTarget("quotazionis1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Quotazioni> getQuotazionis1() {
        return (List<Quotazioni>)readProperty("quotazionis1");
    }


    public void addToQuotazionis2(Quotazioni obj) {
        addToManyTarget("quotazionis2", obj, true);
    }
    public void removeFromQuotazionis2(Quotazioni obj) {
        removeToManyTarget("quotazionis2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Quotazioni> getQuotazionis2() {
        return (List<Quotazioni>)readProperty("quotazionis2");
    }


    public void addToRiferimentiInfocarEliminatis(RiferimentiInfocarEliminati obj) {
        addToManyTarget("riferimentiInfocarEliminatis", obj, true);
    }
    public void removeFromRiferimentiInfocarEliminatis(RiferimentiInfocarEliminati obj) {
        removeToManyTarget("riferimentiInfocarEliminatis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RiferimentiInfocarEliminati> getRiferimentiInfocarEliminatis() {
        return (List<RiferimentiInfocarEliminati>)readProperty("riferimentiInfocarEliminatis");
    }


    public void addToRiferimentiInfocarEliminatis1(RiferimentiInfocarEliminati obj) {
        addToManyTarget("riferimentiInfocarEliminatis1", obj, true);
    }
    public void removeFromRiferimentiInfocarEliminatis1(RiferimentiInfocarEliminati obj) {
        removeToManyTarget("riferimentiInfocarEliminatis1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RiferimentiInfocarEliminati> getRiferimentiInfocarEliminatis1() {
        return (List<RiferimentiInfocarEliminati>)readProperty("riferimentiInfocarEliminatis1");
    }


    public void addToRiferimentiInfocarEliminatis2(RiferimentiInfocarEliminati obj) {
        addToManyTarget("riferimentiInfocarEliminatis2", obj, true);
    }
    public void removeFromRiferimentiInfocarEliminatis2(RiferimentiInfocarEliminati obj) {
        removeToManyTarget("riferimentiInfocarEliminatis2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RiferimentiInfocarEliminati> getRiferimentiInfocarEliminatis2() {
        return (List<RiferimentiInfocarEliminati>)readProperty("riferimentiInfocarEliminatis2");
    }


    public void addToVincolis(Vincoli obj) {
        addToManyTarget("vincolis", obj, true);
    }
    public void removeFromVincolis(Vincoli obj) {
        removeToManyTarget("vincolis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Vincoli> getVincolis() {
        return (List<Vincoli>)readProperty("vincolis");
    }


    public void addToVincolis1(Vincoli obj) {
        addToManyTarget("vincolis1", obj, true);
    }
    public void removeFromVincolis1(Vincoli obj) {
        removeToManyTarget("vincolis1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Vincoli> getVincolis1() {
        return (List<Vincoli>)readProperty("vincolis1");
    }


    public void addToVincolis2(Vincoli obj) {
        addToManyTarget("vincolis2", obj, true);
    }
    public void removeFromVincolis2(Vincoli obj) {
        removeToManyTarget("vincolis2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Vincoli> getVincolis2() {
        return (List<Vincoli>)readProperty("vincolis2");
    }


}
