package model.paser.identificazione.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.identificazione.custom.Base;
import model.paser.identificazione.custom.DettagliNucleoMotore;
import model.paser.identificazione.custom.DettagliNucleoTrasmissione;

/**
 * Class _CambiEPrestazioni was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CambiEPrestazioni extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANNOXX_PK_COLUMN = "ANNOXX";
    public static final String CODALL_PK_COLUMN = "CODALL";
    public static final String CODCOM_PK_COLUMN = "CODCOM";
    public static final String MESEXX_PK_COLUMN = "MESEXX";
    public static final String NUCMOT_PK_COLUMN = "NUCMOT";
    public static final String NUCTRA_PK_COLUMN = "NUCTRA";

    public static final Property<Integer> ACC100 = Property.create("acc100", Integer.class);
    public static final Property<Boolean> ACC100S = Property.create("acc100s", Boolean.class);
    public static final Property<Integer> AUTURB = Property.create("auturb", Integer.class);
    public static final Property<Boolean> AUTURBS = Property.create("auturbs", Boolean.class);
    public static final Property<Integer> AUVCOS = Property.create("auvcos", Integer.class);
    public static final Property<Boolean> AUVCOSS = Property.create("auvcoss", Boolean.class);
    public static final Property<Integer> CAPSER = Property.create("capser", Integer.class);
    public static final Property<Boolean> CAPSERS = Property.create("capsers", Boolean.class);
    public static final Property<Integer> CO2CO1 = Property.create("co2co1", Integer.class);
    public static final Property<Boolean> CO2CO1S = Property.create("co2co1s", Boolean.class);
    public static final Property<Integer> CO2CO2 = Property.create("co2co2", Integer.class);
    public static final Property<Boolean> CO2CO2S = Property.create("co2co2s", Boolean.class);
    public static final Property<Integer> CO2CO3 = Property.create("co2co3", Integer.class);
    public static final Property<Boolean> CO2CO3S = Property.create("co2co3s", Boolean.class);
    public static final Property<String> CODCON = Property.create("codcon", String.class);
    public static final Property<Integer> CODPRG = Property.create("codprg", Integer.class);
    public static final Property<Integer> CONKG1 = Property.create("conkg1", Integer.class);
    public static final Property<Boolean> CONKG1S = Property.create("conkg1s", Boolean.class);
    public static final Property<Integer> CONKG2 = Property.create("conkg2", Integer.class);
    public static final Property<String> CONKG2S = Property.create("conkg2s", String.class);
    public static final Property<Integer> CONKG3 = Property.create("conkg3", Integer.class);
    public static final Property<Boolean> CONKG3S = Property.create("conkg3s", Boolean.class);
    public static final Property<Integer> CONSU1 = Property.create("consu1", Integer.class);
    public static final Property<Boolean> CONSU1S = Property.create("consu1s", Boolean.class);
    public static final Property<Integer> CONSU2 = Property.create("consu2", Integer.class);
    public static final Property<Boolean> CONSU2S = Property.create("consu2s", Boolean.class);
    public static final Property<Integer> CONSU3 = Property.create("consu3", Integer.class);
    public static final Property<Boolean> CONSU3S = Property.create("consu3s", Boolean.class);
    public static final Property<Integer> COPGMI = Property.create("copgmi", Integer.class);
    public static final Property<Integer> COPKGM = Property.create("copkgm", Integer.class);
    public static final Property<Integer> COPPNM = Property.create("coppnm", Integer.class);
    public static final Property<Integer> CSERKG = Property.create("cserkg", Integer.class);
    public static final Property<Boolean> CSERKGS = Property.create("cserkgs", Boolean.class);
    public static final Property<Integer> ELEPCV = Property.create("elepcv", Integer.class);
    public static final Property<Integer> ELEPKW = Property.create("elepkw", Integer.class);
    public static final Property<Integer> NUMPRG = Property.create("numprg", Integer.class);
    public static final Property<Integer> POTCVX = Property.create("potcvx", Integer.class);
    public static final Property<Integer> POTGMI = Property.create("potgmi", Integer.class);
    public static final Property<Integer> POTKWX = Property.create("potkwx", Integer.class);
    public static final Property<Integer> VELCOS = Property.create("velcos", Integer.class);
    public static final Property<Integer> VELMAX = Property.create("velmax", Integer.class);
    public static final Property<Boolean> VELMAXS = Property.create("velmaxs", Boolean.class);
    public static final Property<Base> BASE = Property.create("base", Base.class);
    public static final Property<Base> BASE1 = Property.create("base1", Base.class);
    public static final Property<Base> BASE2 = Property.create("base2", Base.class);
    public static final Property<DettagliNucleoMotore> DETTAGLI_NUCLEO_MOTORE = Property.create("dettagliNucleoMotore", DettagliNucleoMotore.class);
    public static final Property<DettagliNucleoTrasmissione> DETTAGLI_NUCLEO_TRASMISSIONE = Property.create("dettagliNucleoTrasmissione", DettagliNucleoTrasmissione.class);

    public void setAcc100(int acc100) {
        writeProperty("acc100", acc100);
    }
    public int getAcc100() {
        Object value = readProperty("acc100");
        return (value != null) ? (Integer) value : 0;
    }

    public void setAcc100s(boolean acc100s) {
        writeProperty("acc100s", acc100s);
    }
	public boolean isAcc100s() {
        Boolean value = (Boolean)readProperty("acc100s");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setAuturb(int auturb) {
        writeProperty("auturb", auturb);
    }
    public int getAuturb() {
        Object value = readProperty("auturb");
        return (value != null) ? (Integer) value : 0;
    }

    public void setAuturbs(boolean auturbs) {
        writeProperty("auturbs", auturbs);
    }
	public boolean isAuturbs() {
        Boolean value = (Boolean)readProperty("auturbs");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setAuvcos(int auvcos) {
        writeProperty("auvcos", auvcos);
    }
    public int getAuvcos() {
        Object value = readProperty("auvcos");
        return (value != null) ? (Integer) value : 0;
    }

    public void setAuvcoss(boolean auvcoss) {
        writeProperty("auvcoss", auvcoss);
    }
	public boolean isAuvcoss() {
        Boolean value = (Boolean)readProperty("auvcoss");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setCapser(int capser) {
        writeProperty("capser", capser);
    }
    public int getCapser() {
        Object value = readProperty("capser");
        return (value != null) ? (Integer) value : 0;
    }

    public void setCapsers(boolean capsers) {
        writeProperty("capsers", capsers);
    }
	public boolean isCapsers() {
        Boolean value = (Boolean)readProperty("capsers");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setCo2co1(int co2co1) {
        writeProperty("co2co1", co2co1);
    }
    public int getCo2co1() {
        Object value = readProperty("co2co1");
        return (value != null) ? (Integer) value : 0;
    }

    public void setCo2co1s(boolean co2co1s) {
        writeProperty("co2co1s", co2co1s);
    }
	public boolean isCo2co1s() {
        Boolean value = (Boolean)readProperty("co2co1s");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setCo2co2(int co2co2) {
        writeProperty("co2co2", co2co2);
    }
    public int getCo2co2() {
        Object value = readProperty("co2co2");
        return (value != null) ? (Integer) value : 0;
    }

    public void setCo2co2s(boolean co2co2s) {
        writeProperty("co2co2s", co2co2s);
    }
	public boolean isCo2co2s() {
        Boolean value = (Boolean)readProperty("co2co2s");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setCo2co3(int co2co3) {
        writeProperty("co2co3", co2co3);
    }
    public int getCo2co3() {
        Object value = readProperty("co2co3");
        return (value != null) ? (Integer) value : 0;
    }

    public void setCo2co3s(boolean co2co3s) {
        writeProperty("co2co3s", co2co3s);
    }
	public boolean isCo2co3s() {
        Boolean value = (Boolean)readProperty("co2co3s");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setCodcon(String codcon) {
        writeProperty("codcon", codcon);
    }
    public String getCodcon() {
        return (String)readProperty("codcon");
    }

    public void setCodprg(int codprg) {
        writeProperty("codprg", codprg);
    }
    public int getCodprg() {
        Object value = readProperty("codprg");
        return (value != null) ? (Integer) value : 0;
    }

    public void setConkg1(int conkg1) {
        writeProperty("conkg1", conkg1);
    }
    public int getConkg1() {
        Object value = readProperty("conkg1");
        return (value != null) ? (Integer) value : 0;
    }

    public void setConkg1s(boolean conkg1s) {
        writeProperty("conkg1s", conkg1s);
    }
	public boolean isConkg1s() {
        Boolean value = (Boolean)readProperty("conkg1s");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setConkg2(int conkg2) {
        writeProperty("conkg2", conkg2);
    }
    public int getConkg2() {
        Object value = readProperty("conkg2");
        return (value != null) ? (Integer) value : 0;
    }

    public void setConkg2s(String conkg2s) {
        writeProperty("conkg2s", conkg2s);
    }
    public String getConkg2s() {
        return (String)readProperty("conkg2s");
    }

    public void setConkg3(int conkg3) {
        writeProperty("conkg3", conkg3);
    }
    public int getConkg3() {
        Object value = readProperty("conkg3");
        return (value != null) ? (Integer) value : 0;
    }

    public void setConkg3s(boolean conkg3s) {
        writeProperty("conkg3s", conkg3s);
    }
	public boolean isConkg3s() {
        Boolean value = (Boolean)readProperty("conkg3s");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setConsu1(int consu1) {
        writeProperty("consu1", consu1);
    }
    public int getConsu1() {
        Object value = readProperty("consu1");
        return (value != null) ? (Integer) value : 0;
    }

    public void setConsu1s(boolean consu1s) {
        writeProperty("consu1s", consu1s);
    }
	public boolean isConsu1s() {
        Boolean value = (Boolean)readProperty("consu1s");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setConsu2(int consu2) {
        writeProperty("consu2", consu2);
    }
    public int getConsu2() {
        Object value = readProperty("consu2");
        return (value != null) ? (Integer) value : 0;
    }

    public void setConsu2s(boolean consu2s) {
        writeProperty("consu2s", consu2s);
    }
	public boolean isConsu2s() {
        Boolean value = (Boolean)readProperty("consu2s");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setConsu3(int consu3) {
        writeProperty("consu3", consu3);
    }
    public int getConsu3() {
        Object value = readProperty("consu3");
        return (value != null) ? (Integer) value : 0;
    }

    public void setConsu3s(boolean consu3s) {
        writeProperty("consu3s", consu3s);
    }
	public boolean isConsu3s() {
        Boolean value = (Boolean)readProperty("consu3s");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setCopgmi(int copgmi) {
        writeProperty("copgmi", copgmi);
    }
    public int getCopgmi() {
        Object value = readProperty("copgmi");
        return (value != null) ? (Integer) value : 0;
    }

    public void setCopkgm(int copkgm) {
        writeProperty("copkgm", copkgm);
    }
    public int getCopkgm() {
        Object value = readProperty("copkgm");
        return (value != null) ? (Integer) value : 0;
    }

    public void setCoppnm(int coppnm) {
        writeProperty("coppnm", coppnm);
    }
    public int getCoppnm() {
        Object value = readProperty("coppnm");
        return (value != null) ? (Integer) value : 0;
    }

    public void setCserkg(int cserkg) {
        writeProperty("cserkg", cserkg);
    }
    public int getCserkg() {
        Object value = readProperty("cserkg");
        return (value != null) ? (Integer) value : 0;
    }

    public void setCserkgs(boolean cserkgs) {
        writeProperty("cserkgs", cserkgs);
    }
	public boolean isCserkgs() {
        Boolean value = (Boolean)readProperty("cserkgs");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setElepcv(int elepcv) {
        writeProperty("elepcv", elepcv);
    }
    public int getElepcv() {
        Object value = readProperty("elepcv");
        return (value != null) ? (Integer) value : 0;
    }

    public void setElepkw(int elepkw) {
        writeProperty("elepkw", elepkw);
    }
    public int getElepkw() {
        Object value = readProperty("elepkw");
        return (value != null) ? (Integer) value : 0;
    }

    public void setNumprg(int numprg) {
        writeProperty("numprg", numprg);
    }
    public int getNumprg() {
        Object value = readProperty("numprg");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPotcvx(int potcvx) {
        writeProperty("potcvx", potcvx);
    }
    public int getPotcvx() {
        Object value = readProperty("potcvx");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPotgmi(int potgmi) {
        writeProperty("potgmi", potgmi);
    }
    public int getPotgmi() {
        Object value = readProperty("potgmi");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPotkwx(int potkwx) {
        writeProperty("potkwx", potkwx);
    }
    public int getPotkwx() {
        Object value = readProperty("potkwx");
        return (value != null) ? (Integer) value : 0;
    }

    public void setVelcos(int velcos) {
        writeProperty("velcos", velcos);
    }
    public int getVelcos() {
        Object value = readProperty("velcos");
        return (value != null) ? (Integer) value : 0;
    }

    public void setVelmax(int velmax) {
        writeProperty("velmax", velmax);
    }
    public int getVelmax() {
        Object value = readProperty("velmax");
        return (value != null) ? (Integer) value : 0;
    }

    public void setVelmaxs(boolean velmaxs) {
        writeProperty("velmaxs", velmaxs);
    }
	public boolean isVelmaxs() {
        Boolean value = (Boolean)readProperty("velmaxs");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setBase(Base base) {
        setToOneTarget("base", base, true);
    }

    public Base getBase() {
        return (Base)readProperty("base");
    }


    public void setBase1(Base base1) {
        setToOneTarget("base1", base1, true);
    }

    public Base getBase1() {
        return (Base)readProperty("base1");
    }


    public void setBase2(Base base2) {
        setToOneTarget("base2", base2, true);
    }

    public Base getBase2() {
        return (Base)readProperty("base2");
    }


    public void setDettagliNucleoMotore(DettagliNucleoMotore dettagliNucleoMotore) {
        setToOneTarget("dettagliNucleoMotore", dettagliNucleoMotore, true);
    }

    public DettagliNucleoMotore getDettagliNucleoMotore() {
        return (DettagliNucleoMotore)readProperty("dettagliNucleoMotore");
    }


    public void setDettagliNucleoTrasmissione(DettagliNucleoTrasmissione dettagliNucleoTrasmissione) {
        setToOneTarget("dettagliNucleoTrasmissione", dettagliNucleoTrasmissione, true);
    }

    public DettagliNucleoTrasmissione getDettagliNucleoTrasmissione() {
        return (DettagliNucleoTrasmissione)readProperty("dettagliNucleoTrasmissione");
    }


}
