package model.paser.identificazione.cayenne;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.anagrafiche.custom.CodiciCasaAnagrafica;
import model.paser.identificazione.custom.Base;

/**
 * Class _CodiciCasaIdentificazione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CodiciCasaIdentificazione extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANNOXX_PK_COLUMN = "ANNOXX";
    public static final String CODALL_PK_COLUMN = "CODALL";
    public static final String CODCAS_PK_COLUMN = "CODCAS";
    public static final String MESEXX_PK_COLUMN = "MESEXX";

    public static final Property<Date> DATACC = Property.create("datacc", Date.class);
    public static final Property<String> NOTE = Property.create("note", String.class);
    public static final Property<Integer> PRGINS = Property.create("prgins", Integer.class);
    public static final Property<Base> BASE = Property.create("base", Base.class);
    public static final Property<Base> BASE1 = Property.create("base1", Base.class);
    public static final Property<Base> BASE2 = Property.create("base2", Base.class);
    public static final Property<CodiciCasaAnagrafica> CODICI_CASA_ANAGRAFICA = Property.create("codiciCasaAnagrafica", CodiciCasaAnagrafica.class);

    public void setDatacc(Date datacc) {
        writeProperty("datacc", datacc);
    }
    public Date getDatacc() {
        return (Date)readProperty("datacc");
    }

    public void setNote(String note) {
        writeProperty("note", note);
    }
    public String getNote() {
        return (String)readProperty("note");
    }

    public void setPrgins(int prgins) {
        writeProperty("prgins", prgins);
    }
    public int getPrgins() {
        Object value = readProperty("prgins");
        return (value != null) ? (Integer) value : 0;
    }

    public void setBase(Base base) {
        setToOneTarget("base", base, true);
    }

    public Base getBase() {
        return (Base)readProperty("base");
    }


    public void setBase1(Base base1) {
        setToOneTarget("base1", base1, true);
    }

    public Base getBase1() {
        return (Base)readProperty("base1");
    }


    public void setBase2(Base base2) {
        setToOneTarget("base2", base2, true);
    }

    public Base getBase2() {
        return (Base)readProperty("base2");
    }


    public void setCodiciCasaAnagrafica(CodiciCasaAnagrafica codiciCasaAnagrafica) {
        setToOneTarget("codiciCasaAnagrafica", codiciCasaAnagrafica, true);
    }

    public CodiciCasaAnagrafica getCodiciCasaAnagrafica() {
        return (CodiciCasaAnagrafica)readProperty("codiciCasaAnagrafica");
    }


}
