package model.paser.identificazione.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.anagrafiche.custom.NormeAnti_inquinamento;
import model.paser.anagrafiche.custom.TipoCarrozzeria;
import model.paser.anagrafiche.custom.TipoImpianto;
import model.paser.anagrafiche.custom.TipoTetto;
import model.paser.identificazione.custom.Base;

/**
 * Class _DatiTecniciBase was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DatiTecniciBase extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANNOXX_PK_COLUMN = "ANNOXX";
    public static final String CODALL_PK_COLUMN = "CODALL";
    public static final String MESEXX_PK_COLUMN = "MESEXX";

    public static final Property<Integer> ALTEZZ = Property.create("altezz", Integer.class);
    public static final Property<Boolean> ALTEZZS = Property.create("altezzs", Boolean.class);
    public static final Property<Integer> CAPBA1 = Property.create("capba1", Integer.class);
    public static final Property<Boolean> CAPBA1S = Property.create("capba1s", Boolean.class);
    public static final Property<Integer> CAPBA2 = Property.create("capba2", Integer.class);
    public static final Property<Boolean> CAPBA2S = Property.create("capba2s", Boolean.class);
    public static final Property<Integer> CAPBA3 = Property.create("capba3", Integer.class);
    public static final Property<Boolean> CAPBA3S = Property.create("capba3s", Boolean.class);
    public static final Property<Boolean> FLAIBR = Property.create("flaibr", Boolean.class);
    public static final Property<Integer> LARGHE = Property.create("larghe", Integer.class);
    public static final Property<Boolean> LARGHES = Property.create("larghes", Boolean.class);
    public static final Property<Integer> LUNGHE = Property.create("lunghe", Integer.class);
    public static final Property<Boolean> LUNGHES = Property.create("lunghes", Boolean.class);
    public static final Property<Integer> MASPDA = Property.create("maspda", Integer.class);
    public static final Property<Boolean> MASPDAS = Property.create("maspdas", Boolean.class);
    public static final Property<Integer> MASPTT = Property.create("masptt", Integer.class);
    public static final Property<Boolean> MASPTTS = Property.create("masptts", Boolean.class);
    public static final Property<Integer> MASSAR = Property.create("massar", Integer.class);
    public static final Property<Boolean> MASSARS = Property.create("massars", Boolean.class);
    public static final Property<Integer> MASSAX = Property.create("massax", Integer.class);
    public static final Property<Boolean> MASSAXS = Property.create("massaxs", Boolean.class);
    public static final Property<Integer> NUMPOR = Property.create("numpor", Integer.class);
    public static final Property<Integer> NUMPOS = Property.create("numpos", Integer.class);
    public static final Property<Boolean> NUMPOSS = Property.create("numposs", Boolean.class);
    public static final Property<Integer> PASSOX = Property.create("passox", Integer.class);
    public static final Property<Integer> PORTATA = Property.create("portata", Integer.class);
    public static final Property<Boolean> PORTATS = Property.create("portats", Boolean.class);
    public static final Property<Integer> PORTDA = Property.create("portda", Integer.class);
    public static final Property<Boolean> PORTDAS = Property.create("portdas", Boolean.class);
    public static final Property<Integer> POSAGN = Property.create("posagn", Integer.class);
    public static final Property<Boolean> POSAGNS = Property.create("posagns", Boolean.class);
    public static final Property<Integer> POSAGP = Property.create("posagp", Integer.class);
    public static final Property<Boolean> POSAGPS = Property.create("posagps", Boolean.class);
    public static final Property<Integer> POTFIS = Property.create("potfis", Integer.class);
    public static final Property<String> TIPGUI = Property.create("tipgui", String.class);
    public static final Property<Base> BASE = Property.create("base", Base.class);
    public static final Property<Base> BASE1 = Property.create("base1", Base.class);
    public static final Property<Base> BASE2 = Property.create("base2", Base.class);
    public static final Property<NormeAnti_inquinamento> NORME_ANTI_INQUINAMENTO = Property.create("normeAnti_inquinamento", NormeAnti_inquinamento.class);
    public static final Property<TipoCarrozzeria> TIPO_CARROZZERIA = Property.create("tipoCarrozzeria", TipoCarrozzeria.class);
    public static final Property<TipoImpianto> TIPO_IMPIANTO = Property.create("tipoImpianto", TipoImpianto.class);
    public static final Property<TipoTetto> TIPO_TETTO = Property.create("tipoTetto", TipoTetto.class);

    public void setAltezz(int altezz) {
        writeProperty("altezz", altezz);
    }
    public int getAltezz() {
        Object value = readProperty("altezz");
        return (value != null) ? (Integer) value : 0;
    }

    public void setAltezzs(boolean altezzs) {
        writeProperty("altezzs", altezzs);
    }
	public boolean isAltezzs() {
        Boolean value = (Boolean)readProperty("altezzs");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setCapba1(int capba1) {
        writeProperty("capba1", capba1);
    }
    public int getCapba1() {
        Object value = readProperty("capba1");
        return (value != null) ? (Integer) value : 0;
    }

    public void setCapba1s(boolean capba1s) {
        writeProperty("capba1s", capba1s);
    }
	public boolean isCapba1s() {
        Boolean value = (Boolean)readProperty("capba1s");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setCapba2(int capba2) {
        writeProperty("capba2", capba2);
    }
    public int getCapba2() {
        Object value = readProperty("capba2");
        return (value != null) ? (Integer) value : 0;
    }

    public void setCapba2s(boolean capba2s) {
        writeProperty("capba2s", capba2s);
    }
	public boolean isCapba2s() {
        Boolean value = (Boolean)readProperty("capba2s");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setCapba3(int capba3) {
        writeProperty("capba3", capba3);
    }
    public int getCapba3() {
        Object value = readProperty("capba3");
        return (value != null) ? (Integer) value : 0;
    }

    public void setCapba3s(boolean capba3s) {
        writeProperty("capba3s", capba3s);
    }
	public boolean isCapba3s() {
        Boolean value = (Boolean)readProperty("capba3s");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setFlaibr(boolean flaibr) {
        writeProperty("flaibr", flaibr);
    }
	public boolean isFlaibr() {
        Boolean value = (Boolean)readProperty("flaibr");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setLarghe(int larghe) {
        writeProperty("larghe", larghe);
    }
    public int getLarghe() {
        Object value = readProperty("larghe");
        return (value != null) ? (Integer) value : 0;
    }

    public void setLarghes(boolean larghes) {
        writeProperty("larghes", larghes);
    }
	public boolean isLarghes() {
        Boolean value = (Boolean)readProperty("larghes");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setLunghe(int lunghe) {
        writeProperty("lunghe", lunghe);
    }
    public int getLunghe() {
        Object value = readProperty("lunghe");
        return (value != null) ? (Integer) value : 0;
    }

    public void setLunghes(boolean lunghes) {
        writeProperty("lunghes", lunghes);
    }
	public boolean isLunghes() {
        Boolean value = (Boolean)readProperty("lunghes");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setMaspda(int maspda) {
        writeProperty("maspda", maspda);
    }
    public int getMaspda() {
        Object value = readProperty("maspda");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMaspdas(boolean maspdas) {
        writeProperty("maspdas", maspdas);
    }
	public boolean isMaspdas() {
        Boolean value = (Boolean)readProperty("maspdas");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setMasptt(int masptt) {
        writeProperty("masptt", masptt);
    }
    public int getMasptt() {
        Object value = readProperty("masptt");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMasptts(boolean masptts) {
        writeProperty("masptts", masptts);
    }
	public boolean isMasptts() {
        Boolean value = (Boolean)readProperty("masptts");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setMassar(int massar) {
        writeProperty("massar", massar);
    }
    public int getMassar() {
        Object value = readProperty("massar");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMassars(boolean massars) {
        writeProperty("massars", massars);
    }
	public boolean isMassars() {
        Boolean value = (Boolean)readProperty("massars");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setMassax(int massax) {
        writeProperty("massax", massax);
    }
    public int getMassax() {
        Object value = readProperty("massax");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMassaxs(boolean massaxs) {
        writeProperty("massaxs", massaxs);
    }
	public boolean isMassaxs() {
        Boolean value = (Boolean)readProperty("massaxs");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setNumpor(int numpor) {
        writeProperty("numpor", numpor);
    }
    public int getNumpor() {
        Object value = readProperty("numpor");
        return (value != null) ? (Integer) value : 0;
    }

    public void setNumpos(int numpos) {
        writeProperty("numpos", numpos);
    }
    public int getNumpos() {
        Object value = readProperty("numpos");
        return (value != null) ? (Integer) value : 0;
    }

    public void setNumposs(boolean numposs) {
        writeProperty("numposs", numposs);
    }
	public boolean isNumposs() {
        Boolean value = (Boolean)readProperty("numposs");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setPassox(int passox) {
        writeProperty("passox", passox);
    }
    public int getPassox() {
        Object value = readProperty("passox");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPortata(int portata) {
        writeProperty("portata", portata);
    }
    public int getPortata() {
        Object value = readProperty("portata");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPortats(boolean portats) {
        writeProperty("portats", portats);
    }
	public boolean isPortats() {
        Boolean value = (Boolean)readProperty("portats");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setPortda(int portda) {
        writeProperty("portda", portda);
    }
    public int getPortda() {
        Object value = readProperty("portda");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPortdas(boolean portdas) {
        writeProperty("portdas", portdas);
    }
	public boolean isPortdas() {
        Boolean value = (Boolean)readProperty("portdas");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setPosagn(int posagn) {
        writeProperty("posagn", posagn);
    }
    public int getPosagn() {
        Object value = readProperty("posagn");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPosagns(boolean posagns) {
        writeProperty("posagns", posagns);
    }
	public boolean isPosagns() {
        Boolean value = (Boolean)readProperty("posagns");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setPosagp(int posagp) {
        writeProperty("posagp", posagp);
    }
    public int getPosagp() {
        Object value = readProperty("posagp");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPosagps(boolean posagps) {
        writeProperty("posagps", posagps);
    }
	public boolean isPosagps() {
        Boolean value = (Boolean)readProperty("posagps");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setPotfis(int potfis) {
        writeProperty("potfis", potfis);
    }
    public int getPotfis() {
        Object value = readProperty("potfis");
        return (value != null) ? (Integer) value : 0;
    }

    public void setTipgui(String tipgui) {
        writeProperty("tipgui", tipgui);
    }
    public String getTipgui() {
        return (String)readProperty("tipgui");
    }

    public void setBase(Base base) {
        setToOneTarget("base", base, true);
    }

    public Base getBase() {
        return (Base)readProperty("base");
    }


    public void setBase1(Base base1) {
        setToOneTarget("base1", base1, true);
    }

    public Base getBase1() {
        return (Base)readProperty("base1");
    }


    public void setBase2(Base base2) {
        setToOneTarget("base2", base2, true);
    }

    public Base getBase2() {
        return (Base)readProperty("base2");
    }


    public void setNormeAnti_inquinamento(NormeAnti_inquinamento normeAnti_inquinamento) {
        setToOneTarget("normeAnti_inquinamento", normeAnti_inquinamento, true);
    }

    public NormeAnti_inquinamento getNormeAnti_inquinamento() {
        return (NormeAnti_inquinamento)readProperty("normeAnti_inquinamento");
    }


    public void setTipoCarrozzeria(TipoCarrozzeria tipoCarrozzeria) {
        setToOneTarget("tipoCarrozzeria", tipoCarrozzeria, true);
    }

    public TipoCarrozzeria getTipoCarrozzeria() {
        return (TipoCarrozzeria)readProperty("tipoCarrozzeria");
    }


    public void setTipoImpianto(TipoImpianto tipoImpianto) {
        setToOneTarget("tipoImpianto", tipoImpianto, true);
    }

    public TipoImpianto getTipoImpianto() {
        return (TipoImpianto)readProperty("tipoImpianto");
    }


    public void setTipoTetto(TipoTetto tipoTetto) {
        setToOneTarget("tipoTetto", tipoTetto, true);
    }

    public TipoTetto getTipoTetto() {
        return (TipoTetto)readProperty("tipoTetto");
    }


}
