package model.paser.identificazione.cayenne;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.identificazione.custom.CambiEPrestazioni;

/**
 * Class _DettagliNucleoTrasmissione was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DettagliNucleoTrasmissione extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String NUCTRA_PK_COLUMN = "NUCTRA";

    public static final Property<String> CODCAM = Property.create("codcam", String.class);
    public static final Property<String> CODTRA = Property.create("codtra", String.class);
    public static final Property<Integer> MARCEX = Property.create("marcex", Integer.class);
    public static final Property<List<CambiEPrestazioni>> CAMBI_EPRESTAZIONIS = Property.create("cambiEPrestazionis", List.class);

    public void setCodcam(String codcam) {
        writeProperty("codcam", codcam);
    }
    public String getCodcam() {
        return (String)readProperty("codcam");
    }

    public void setCodtra(String codtra) {
        writeProperty("codtra", codtra);
    }
    public String getCodtra() {
        return (String)readProperty("codtra");
    }

    public void setMarcex(int marcex) {
        writeProperty("marcex", marcex);
    }
    public int getMarcex() {
        Object value = readProperty("marcex");
        return (value != null) ? (Integer) value : 0;
    }

    public void addToCambiEPrestazionis(CambiEPrestazioni obj) {
        addToManyTarget("cambiEPrestazionis", obj, true);
    }
    public void removeFromCambiEPrestazionis(CambiEPrestazioni obj) {
        removeToManyTarget("cambiEPrestazionis", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CambiEPrestazioni> getCambiEPrestazionis() {
        return (List<CambiEPrestazioni>)readProperty("cambiEPrestazionis");
    }


}
