package model.paser.identificazione.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.identificazione.custom.Base;

/**
 * Class _DettaglioSegmenti was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DettaglioSegmenti extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String CODALL_PK_COLUMN = "CODALL";

    public static final Property<String> CODSEG = Property.create("codseg", String.class);
    public static final Property<Base> BASE = Property.create("base", Base.class);

    public void setCodseg(String codseg) {
        writeProperty("codseg", codseg);
    }
    public String getCodseg() {
        return (String)readProperty("codseg");
    }

    public void setBase(Base base) {
        setToOneTarget("base", base, true);
    }

    public Base getBase() {
        return (Base)readProperty("base");
    }


}
