package model.paser.identificazione.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.identificazione.custom.Base;

/**
 * Class _InformazioniAggiuntive was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _InformazioniAggiuntive extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANNOXX_PK_COLUMN = "ANNOXX";
    public static final String CODALL_PK_COLUMN = "CODALL";
    public static final String MESEXX_PK_COLUMN = "MESEXX";

    public static final Property<String> FILLER = Property.create("filler", String.class);
    public static final Property<Boolean> FLASCO = Property.create("flasco", Boolean.class);
    public static final Property<Boolean> FLMFLE = Property.create("flmfle", Boolean.class);
    public static final Property<Boolean> FLMPIV = Property.create("flmpiv", Boolean.class);
    public static final Property<Boolean> FLMPRI = Property.create("flmpri", Boolean.class);
    public static final Property<Base> BASE = Property.create("base", Base.class);
    public static final Property<Base> BASE1 = Property.create("base1", Base.class);
    public static final Property<Base> BASE2 = Property.create("base2", Base.class);

    public void setFiller(String filler) {
        writeProperty("filler", filler);
    }
    public String getFiller() {
        return (String)readProperty("filler");
    }

    public void setFlasco(boolean flasco) {
        writeProperty("flasco", flasco);
    }
	public boolean isFlasco() {
        Boolean value = (Boolean)readProperty("flasco");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setFlmfle(boolean flmfle) {
        writeProperty("flmfle", flmfle);
    }
	public boolean isFlmfle() {
        Boolean value = (Boolean)readProperty("flmfle");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setFlmpiv(boolean flmpiv) {
        writeProperty("flmpiv", flmpiv);
    }
	public boolean isFlmpiv() {
        Boolean value = (Boolean)readProperty("flmpiv");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setFlmpri(boolean flmpri) {
        writeProperty("flmpri", flmpri);
    }
	public boolean isFlmpri() {
        Boolean value = (Boolean)readProperty("flmpri");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setBase(Base base) {
        setToOneTarget("base", base, true);
    }

    public Base getBase() {
        return (Base)readProperty("base");
    }


    public void setBase1(Base base1) {
        setToOneTarget("base1", base1, true);
    }

    public Base getBase1() {
        return (Base)readProperty("base1");
    }


    public void setBase2(Base base2) {
        setToOneTarget("base2", base2, true);
    }

    public Base getBase2() {
        return (Base)readProperty("base2");
    }


}
