package model.paser.identificazione.cayenne;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import model.paser.identificazione.custom.Base;

/**
 * Class _ListiniNuovo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ListiniNuovo extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ANNOXX_PK_COLUMN = "ANNOXX";
    public static final String CODALL_PK_COLUMN = "CODALL";
    public static final String DATALI_PK_COLUMN = "DATALI";
    public static final String MESEXX_PK_COLUMN = "MESEXX";

    public static final Property<Double> CIMEUR = Property.create("cimeur", Double.class);
    public static final Property<Boolean> CIMSTI = Property.create("cimsti", Boolean.class);
    public static final Property<Double> FRCEUR = Property.create("frceur", Double.class);
    public static final Property<Boolean> FRCSTI = Property.create("frcsti", Boolean.class);
    public static final Property<Base> BASE = Property.create("base", Base.class);
    public static final Property<Base> BASE1 = Property.create("base1", Base.class);
    public static final Property<Base> BASE2 = Property.create("base2", Base.class);

    public void setCimeur(double cimeur) {
        writeProperty("cimeur", cimeur);
    }
    public double getCimeur() {
        Object value = readProperty("cimeur");
        return (value != null) ? (Double) value : 0;
    }

    public void setCimsti(boolean cimsti) {
        writeProperty("cimsti", cimsti);
    }
	public boolean isCimsti() {
        Boolean value = (Boolean)readProperty("cimsti");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setFrceur(double frceur) {
        writeProperty("frceur", frceur);
    }
    public double getFrceur() {
        Object value = readProperty("frceur");
        return (value != null) ? (Double) value : 0;
    }

    public void setFrcsti(boolean frcsti) {
        writeProperty("frcsti", frcsti);
    }
	public boolean isFrcsti() {
        Boolean value = (Boolean)readProperty("frcsti");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setBase(Base base) {
        setToOneTarget("base", base, true);
    }

    public Base getBase() {
        return (Base)readProperty("base");
    }


    public void setBase1(Base base1) {
        setToOneTarget("base1", base1, true);
    }

    public Base getBase1() {
        return (Base)readProperty("base1");
    }


    public void setBase2(Base base2) {
        setToOneTarget("base2", base2, true);
    }

    public Base getBase2() {
        return (Base)readProperty("base2");
    }


}
